//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class ActionScreen
{
    public Label labelCurrentCastleGold { get; private set; }

    public Label labelCurrentAP { get; private set; }

    public Label labelCurrentPersonalGold { get; private set; }

    public Label labelPhaseTitle { get; private set; }

    public Label labelPhaseSubtitle { get; private set; }

    public VisualElement StrategyPhaseHeader { get; private set; }

    public VisualElement PersonalPhaseHeader { get; private set; }

    public VisualElement PersonalActionGaugeMaxBar { get; private set; }

    public VisualElement PersonalActionGaugeCurrentBar { get; private set; }

    public VisualElement PersonalActionGaugeBar { get; private set; }

    public VisualElement StrategyActionGaugeMaxBar { get; private set; }

    public VisualElement StrategyActionGaugeCurrentBar { get; private set; }

    public Label labelStrategyActionGuageCaption { get; private set; }

    public VisualElement StrategyActionGaugeBar { get; private set; }

    public Button buttonResume { get; private set; }

    public Label labelGameDate { get; private set; }

    public Button buttonSystem { get; private set; }

    public Label labelCost { get; private set; }

    public Label labelActionDescription { get; private set; }

    public VisualElement StrategyActionButtons { get; private set; }

    public VisualElement PersonalActionButtons { get; private set; }

    public Button buttonMoveToMyCastle { get; private set; }

    public VisualElement ActionPanel { get; private set; }

    public VisualElement NoActionPanel { get; private set; }

    public VisualElement ActivePhaseContent { get; private set; }

    public VisualElement ProgressPhaseContent { get; private set; }

    public Button buttonTurnEnd { get; private set; }

    public Button buttonToggleActionPanelFolding { get; private set; }

    public VisualElement ActionPanelContent { get; private set; }

    public CastleInfoPanel CastleInfoPanel { get; private set; }

    public VisualElement Root { get; private set; }

    public ActionScreen(VisualElement root)
    {
        Root = root;
        labelCurrentCastleGold = Root?.Q<Label>("labelCurrentCastleGold");
        labelCurrentAP = Root?.Q<Label>("labelCurrentAP");
        labelCurrentPersonalGold = Root?.Q<Label>("labelCurrentPersonalGold");
        labelPhaseTitle = Root?.Q<Label>("labelPhaseTitle");
        labelPhaseSubtitle = Root?.Q<Label>("labelPhaseSubtitle");
        StrategyPhaseHeader = Root?.Q<VisualElement>("StrategyPhaseHeader");
        PersonalPhaseHeader = Root?.Q<VisualElement>("PersonalPhaseHeader");
        PersonalActionGaugeMaxBar = Root?.Q<VisualElement>("PersonalActionGaugeMaxBar");
        PersonalActionGaugeCurrentBar = Root?.Q<VisualElement>("PersonalActionGaugeCurrentBar");
        PersonalActionGaugeBar = Root?.Q<VisualElement>("PersonalActionGaugeBar");
        StrategyActionGaugeMaxBar = Root?.Q<VisualElement>("StrategyActionGaugeMaxBar");
        StrategyActionGaugeCurrentBar = Root?.Q<VisualElement>("StrategyActionGaugeCurrentBar");
        labelStrategyActionGuageCaption = Root?.Q<Label>("labelStrategyActionGuageCaption");
        StrategyActionGaugeBar = Root?.Q<VisualElement>("StrategyActionGaugeBar");
        buttonResume = Root?.Q<Button>("buttonResume");
        labelGameDate = Root?.Q<Label>("labelGameDate");
        buttonSystem = Root?.Q<Button>("buttonSystem");
        labelCost = Root?.Q<Label>("labelCost");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        StrategyActionButtons = Root?.Q<VisualElement>("StrategyActionButtons");
        PersonalActionButtons = Root?.Q<VisualElement>("PersonalActionButtons");
        buttonMoveToMyCastle = Root?.Q<Button>("buttonMoveToMyCastle");
        ActionPanel = Root?.Q<VisualElement>("ActionPanel");
        NoActionPanel = Root?.Q<VisualElement>("NoActionPanel");
        ActivePhaseContent = Root?.Q<VisualElement>("ActivePhaseContent");
        ProgressPhaseContent = Root?.Q<VisualElement>("ProgressPhaseContent");
        buttonTurnEnd = Root?.Q<Button>("buttonTurnEnd");
        buttonToggleActionPanelFolding = Root?.Q<Button>("buttonToggleActionPanelFolding");
        ActionPanelContent = Root?.Q<VisualElement>("ActionPanelContent");
        CastleInfoPanel = new CastleInfoPanel(Root?.Q<VisualElement>("CastleInfoPanel"));
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelCurrentCastleGold = Root?.Q<Label>("labelCurrentCastleGold");
        labelCurrentAP = Root?.Q<Label>("labelCurrentAP");
        labelCurrentPersonalGold = Root?.Q<Label>("labelCurrentPersonalGold");
        labelPhaseTitle = Root?.Q<Label>("labelPhaseTitle");
        labelPhaseSubtitle = Root?.Q<Label>("labelPhaseSubtitle");
        StrategyPhaseHeader = Root?.Q<VisualElement>("StrategyPhaseHeader");
        PersonalPhaseHeader = Root?.Q<VisualElement>("PersonalPhaseHeader");
        PersonalActionGaugeMaxBar = Root?.Q<VisualElement>("PersonalActionGaugeMaxBar");
        PersonalActionGaugeCurrentBar = Root?.Q<VisualElement>("PersonalActionGaugeCurrentBar");
        PersonalActionGaugeBar = Root?.Q<VisualElement>("PersonalActionGaugeBar");
        StrategyActionGaugeMaxBar = Root?.Q<VisualElement>("StrategyActionGaugeMaxBar");
        StrategyActionGaugeCurrentBar = Root?.Q<VisualElement>("StrategyActionGaugeCurrentBar");
        labelStrategyActionGuageCaption = Root?.Q<Label>("labelStrategyActionGuageCaption");
        StrategyActionGaugeBar = Root?.Q<VisualElement>("StrategyActionGaugeBar");
        buttonResume = Root?.Q<Button>("buttonResume");
        labelGameDate = Root?.Q<Label>("labelGameDate");
        buttonSystem = Root?.Q<Button>("buttonSystem");
        labelCost = Root?.Q<Label>("labelCost");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        StrategyActionButtons = Root?.Q<VisualElement>("StrategyActionButtons");
        PersonalActionButtons = Root?.Q<VisualElement>("PersonalActionButtons");
        buttonMoveToMyCastle = Root?.Q<Button>("buttonMoveToMyCastle");
        ActionPanel = Root?.Q<VisualElement>("ActionPanel");
        NoActionPanel = Root?.Q<VisualElement>("NoActionPanel");
        ActivePhaseContent = Root?.Q<VisualElement>("ActivePhaseContent");
        ProgressPhaseContent = Root?.Q<VisualElement>("ProgressPhaseContent");
        buttonTurnEnd = Root?.Q<Button>("buttonTurnEnd");
        buttonToggleActionPanelFolding = Root?.Q<Button>("buttonToggleActionPanelFolding");
        ActionPanelContent = Root?.Q<VisualElement>("ActionPanelContent");
        CastleInfoPanel = new CastleInfoPanel(Root?.Q<VisualElement>("CastleInfoPanel"));
    }
}