//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class BattleSoldierIconAttackSide
{
    public Label labelHP { get; private set; }

    public VisualElement HPBarValue { get; private set; }

    public VisualElement HPBarBackground { get; private set; }

    public VisualElement HPBar { get; private set; }

    public Image SoldierImage { get; private set; }

    public VisualElement Soldier { get; private set; }

    public VisualElement Root { get; }

    public BattleSoldierIconAttackSide(VisualElement root)
    {
        Root = root;
        labelHP = Root?.Q<Label>("labelHP");
        HPBarValue = Root?.Q<VisualElement>("HPBarValue");
        HPBarBackground = Root?.Q<VisualElement>("HPBarBackground");
        HPBar = Root?.Q<VisualElement>("HPBar");
        SoldierImage = Root?.Q<Image>("SoldierImage");
        Soldier = Root?.Q<VisualElement>("Soldier");
    }
}