//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class BattleWindow
{
    public Label labelAttackerNameCaption { get; private set; }

    public Label AttackerName { get; private set; }

    public Label labelDefenderNameCaption { get; private set; }

    public Label DefenderName { get; private set; }

    public Label labelBattleType { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier10 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier11 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier12 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier13 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier14 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier05 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier06 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier07 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier08 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier09 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier00 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier01 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier02 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier03 { get; private set; }

    public BattleSoldierIconAttackSide AttackerSoldier04 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier00 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier01 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier02 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier03 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier04 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier05 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier06 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier07 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier08 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier09 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier10 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier11 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier12 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier13 { get; private set; }

    public BattleSoldierIconDefenceSide DefenderSoldier14 { get; private set; }

    public VisualElement AttackerSoldiers { get; private set; }

    public VisualElement DefenderSoldiers { get; private set; }

    public Label labelAttackerAttackCaption { get; private set; }

    public Label labelAttackerAttack { get; private set; }

    public Label labelAttackerIntelligenseCaption { get; private set; }

    public Label labelAttackerIntelligense { get; private set; }

    public VisualElement imageAttacker { get; private set; }

    public Label labelAttackerTerrainCaption { get; private set; }

    public Label labelAttackerTerrain { get; private set; }

    public VisualElement AttackerTacticsBar1 { get; private set; }

    public VisualElement AttackerTacticsBar2 { get; private set; }

    public VisualElement AttackerTacticsBar3 { get; private set; }

    public Label labelAttackerTacticsCaption { get; private set; }

    public VisualElement AttackerTacticsGauge { get; private set; }

    public VisualElement AttackerRetreatBar { get; private set; }

    public Label labelAttackerRetreatCaption { get; private set; }

    public VisualElement AttackerRetreatGauge { get; private set; }

    public Label labelDefenderDefenceCaption { get; private set; }

    public Label labelDefenderDefence { get; private set; }

    public Label labelDefenderIntelligenseCaption { get; private set; }

    public Label labelDefenderIntelligense { get; private set; }

    public VisualElement imageDefender { get; private set; }

    public Label labelDefenderTerrainCaption { get; private set; }

    public Label labelDefenderTerrain { get; private set; }

    public VisualElement DefenderTacticsBar1 { get; private set; }

    public VisualElement DefenderTacticsBar2 { get; private set; }

    public VisualElement DefenderTacticsBar3 { get; private set; }

    public VisualElement DefenderTacticsGauge { get; private set; }

    public Label labelDefenderTacticsCaption { get; private set; }

    public VisualElement DefenderRetreatBar { get; private set; }

    public VisualElement DefenderRetreatGauge { get; private set; }

    public Label labelDefenderRetreatCaption { get; private set; }

    public Button buttonAttack { get; private set; }

    public Button buttonSwap12 { get; private set; }

    public Button buttonSwap23 { get; private set; }

    public Button buttonRest { get; private set; }

    public Button buttonRetreat { get; private set; }

    public Button buttonResult { get; private set; }

    public VisualElement Root { get; private set; }

    public BattleWindow(VisualElement root)
    {
        Root = root;
        labelAttackerNameCaption = Root?.Q<Label>("labelAttackerNameCaption");
        AttackerName = Root?.Q<Label>("AttackerName");
        labelDefenderNameCaption = Root?.Q<Label>("labelDefenderNameCaption");
        DefenderName = Root?.Q<Label>("DefenderName");
        labelBattleType = Root?.Q<Label>("labelBattleType");
        AttackerSoldier10 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier10"));
        AttackerSoldier11 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier11"));
        AttackerSoldier12 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier12"));
        AttackerSoldier13 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier13"));
        AttackerSoldier14 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier14"));
        AttackerSoldier05 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier05"));
        AttackerSoldier06 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier06"));
        AttackerSoldier07 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier07"));
        AttackerSoldier08 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier08"));
        AttackerSoldier09 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier09"));
        AttackerSoldier00 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier00"));
        AttackerSoldier01 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier01"));
        AttackerSoldier02 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier02"));
        AttackerSoldier03 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier03"));
        AttackerSoldier04 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier04"));
        DefenderSoldier00 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier00"));
        DefenderSoldier01 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier01"));
        DefenderSoldier02 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier02"));
        DefenderSoldier03 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier03"));
        DefenderSoldier04 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier04"));
        DefenderSoldier05 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier05"));
        DefenderSoldier06 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier06"));
        DefenderSoldier07 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier07"));
        DefenderSoldier08 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier08"));
        DefenderSoldier09 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier09"));
        DefenderSoldier10 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier10"));
        DefenderSoldier11 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier11"));
        DefenderSoldier12 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier12"));
        DefenderSoldier13 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier13"));
        DefenderSoldier14 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier14"));
        AttackerSoldiers = Root?.Q<VisualElement>("AttackerSoldiers");
        DefenderSoldiers = Root?.Q<VisualElement>("DefenderSoldiers");
        labelAttackerAttackCaption = Root?.Q<Label>("labelAttackerAttackCaption");
        labelAttackerAttack = Root?.Q<Label>("labelAttackerAttack");
        labelAttackerIntelligenseCaption = Root?.Q<Label>("labelAttackerIntelligenseCaption");
        labelAttackerIntelligense = Root?.Q<Label>("labelAttackerIntelligense");
        imageAttacker = Root?.Q<VisualElement>("imageAttacker");
        labelAttackerTerrainCaption = Root?.Q<Label>("labelAttackerTerrainCaption");
        labelAttackerTerrain = Root?.Q<Label>("labelAttackerTerrain");
        AttackerTacticsBar1 = Root?.Q<VisualElement>("AttackerTacticsBar1");
        AttackerTacticsBar2 = Root?.Q<VisualElement>("AttackerTacticsBar2");
        AttackerTacticsBar3 = Root?.Q<VisualElement>("AttackerTacticsBar3");
        labelAttackerTacticsCaption = Root?.Q<Label>("labelAttackerTacticsCaption");
        AttackerTacticsGauge = Root?.Q<VisualElement>("AttackerTacticsGauge");
        AttackerRetreatBar = Root?.Q<VisualElement>("AttackerRetreatBar");
        labelAttackerRetreatCaption = Root?.Q<Label>("labelAttackerRetreatCaption");
        AttackerRetreatGauge = Root?.Q<VisualElement>("AttackerRetreatGauge");
        labelDefenderDefenceCaption = Root?.Q<Label>("labelDefenderDefenceCaption");
        labelDefenderDefence = Root?.Q<Label>("labelDefenderDefence");
        labelDefenderIntelligenseCaption = Root?.Q<Label>("labelDefenderIntelligenseCaption");
        labelDefenderIntelligense = Root?.Q<Label>("labelDefenderIntelligense");
        imageDefender = Root?.Q<VisualElement>("imageDefender");
        labelDefenderTerrainCaption = Root?.Q<Label>("labelDefenderTerrainCaption");
        labelDefenderTerrain = Root?.Q<Label>("labelDefenderTerrain");
        DefenderTacticsBar1 = Root?.Q<VisualElement>("DefenderTacticsBar1");
        DefenderTacticsBar2 = Root?.Q<VisualElement>("DefenderTacticsBar2");
        DefenderTacticsBar3 = Root?.Q<VisualElement>("DefenderTacticsBar3");
        DefenderTacticsGauge = Root?.Q<VisualElement>("DefenderTacticsGauge");
        labelDefenderTacticsCaption = Root?.Q<Label>("labelDefenderTacticsCaption");
        DefenderRetreatBar = Root?.Q<VisualElement>("DefenderRetreatBar");
        DefenderRetreatGauge = Root?.Q<VisualElement>("DefenderRetreatGauge");
        labelDefenderRetreatCaption = Root?.Q<Label>("labelDefenderRetreatCaption");
        buttonAttack = Root?.Q<Button>("buttonAttack");
        buttonSwap12 = Root?.Q<Button>("buttonSwap12");
        buttonSwap23 = Root?.Q<Button>("buttonSwap23");
        buttonRest = Root?.Q<Button>("buttonRest");
        buttonRetreat = Root?.Q<Button>("buttonRetreat");
        buttonResult = Root?.Q<Button>("buttonResult");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelAttackerNameCaption = Root?.Q<Label>("labelAttackerNameCaption");
        AttackerName = Root?.Q<Label>("AttackerName");
        labelDefenderNameCaption = Root?.Q<Label>("labelDefenderNameCaption");
        DefenderName = Root?.Q<Label>("DefenderName");
        labelBattleType = Root?.Q<Label>("labelBattleType");
        AttackerSoldier10 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier10"));
        AttackerSoldier11 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier11"));
        AttackerSoldier12 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier12"));
        AttackerSoldier13 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier13"));
        AttackerSoldier14 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier14"));
        AttackerSoldier05 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier05"));
        AttackerSoldier06 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier06"));
        AttackerSoldier07 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier07"));
        AttackerSoldier08 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier08"));
        AttackerSoldier09 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier09"));
        AttackerSoldier00 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier00"));
        AttackerSoldier01 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier01"));
        AttackerSoldier02 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier02"));
        AttackerSoldier03 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier03"));
        AttackerSoldier04 = new BattleSoldierIconAttackSide(Root?.Q<VisualElement>("AttackerSoldier04"));
        DefenderSoldier00 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier00"));
        DefenderSoldier01 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier01"));
        DefenderSoldier02 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier02"));
        DefenderSoldier03 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier03"));
        DefenderSoldier04 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier04"));
        DefenderSoldier05 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier05"));
        DefenderSoldier06 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier06"));
        DefenderSoldier07 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier07"));
        DefenderSoldier08 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier08"));
        DefenderSoldier09 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier09"));
        DefenderSoldier10 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier10"));
        DefenderSoldier11 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier11"));
        DefenderSoldier12 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier12"));
        DefenderSoldier13 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier13"));
        DefenderSoldier14 = new BattleSoldierIconDefenceSide(Root?.Q<VisualElement>("DefenderSoldier14"));
        AttackerSoldiers = Root?.Q<VisualElement>("AttackerSoldiers");
        DefenderSoldiers = Root?.Q<VisualElement>("DefenderSoldiers");
        labelAttackerAttackCaption = Root?.Q<Label>("labelAttackerAttackCaption");
        labelAttackerAttack = Root?.Q<Label>("labelAttackerAttack");
        labelAttackerIntelligenseCaption = Root?.Q<Label>("labelAttackerIntelligenseCaption");
        labelAttackerIntelligense = Root?.Q<Label>("labelAttackerIntelligense");
        imageAttacker = Root?.Q<VisualElement>("imageAttacker");
        labelAttackerTerrainCaption = Root?.Q<Label>("labelAttackerTerrainCaption");
        labelAttackerTerrain = Root?.Q<Label>("labelAttackerTerrain");
        AttackerTacticsBar1 = Root?.Q<VisualElement>("AttackerTacticsBar1");
        AttackerTacticsBar2 = Root?.Q<VisualElement>("AttackerTacticsBar2");
        AttackerTacticsBar3 = Root?.Q<VisualElement>("AttackerTacticsBar3");
        labelAttackerTacticsCaption = Root?.Q<Label>("labelAttackerTacticsCaption");
        AttackerTacticsGauge = Root?.Q<VisualElement>("AttackerTacticsGauge");
        AttackerRetreatBar = Root?.Q<VisualElement>("AttackerRetreatBar");
        labelAttackerRetreatCaption = Root?.Q<Label>("labelAttackerRetreatCaption");
        AttackerRetreatGauge = Root?.Q<VisualElement>("AttackerRetreatGauge");
        labelDefenderDefenceCaption = Root?.Q<Label>("labelDefenderDefenceCaption");
        labelDefenderDefence = Root?.Q<Label>("labelDefenderDefence");
        labelDefenderIntelligenseCaption = Root?.Q<Label>("labelDefenderIntelligenseCaption");
        labelDefenderIntelligense = Root?.Q<Label>("labelDefenderIntelligense");
        imageDefender = Root?.Q<VisualElement>("imageDefender");
        labelDefenderTerrainCaption = Root?.Q<Label>("labelDefenderTerrainCaption");
        labelDefenderTerrain = Root?.Q<Label>("labelDefenderTerrain");
        DefenderTacticsBar1 = Root?.Q<VisualElement>("DefenderTacticsBar1");
        DefenderTacticsBar2 = Root?.Q<VisualElement>("DefenderTacticsBar2");
        DefenderTacticsBar3 = Root?.Q<VisualElement>("DefenderTacticsBar3");
        DefenderTacticsGauge = Root?.Q<VisualElement>("DefenderTacticsGauge");
        labelDefenderTacticsCaption = Root?.Q<Label>("labelDefenderTacticsCaption");
        DefenderRetreatBar = Root?.Q<VisualElement>("DefenderRetreatBar");
        DefenderRetreatGauge = Root?.Q<VisualElement>("DefenderRetreatGauge");
        labelDefenderRetreatCaption = Root?.Q<Label>("labelDefenderRetreatCaption");
        buttonAttack = Root?.Q<Button>("buttonAttack");
        buttonSwap12 = Root?.Q<Button>("buttonSwap12");
        buttonSwap23 = Root?.Q<Button>("buttonSwap23");
        buttonRest = Root?.Q<Button>("buttonRest");
        buttonRetreat = Root?.Q<Button>("buttonRetreat");
        buttonResult = Root?.Q<Button>("buttonResult");
    }
}