//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CameraMovementArea
{
    public VisualElement TopScrollZone { get; private set; }

    public VisualElement BottomScrollZone { get; private set; }

    public VisualElement LeftScrollZone { get; private set; }

    public VisualElement RightScrollZone { get; private set; }

    public VisualElement Root { get; private set; }

    public CameraMovementArea(VisualElement root)
    {
        Root = root;
        TopScrollZone = Root?.Q<VisualElement>("TopScrollZone");
        BottomScrollZone = Root?.Q<VisualElement>("BottomScrollZone");
        LeftScrollZone = Root?.Q<VisualElement>("LeftScrollZone");
        RightScrollZone = Root?.Q<VisualElement>("RightScrollZone");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        TopScrollZone = Root?.Q<VisualElement>("TopScrollZone");
        BottomScrollZone = Root?.Q<VisualElement>("BottomScrollZone");
        LeftScrollZone = Root?.Q<VisualElement>("LeftScrollZone");
        RightScrollZone = Root?.Q<VisualElement>("RightScrollZone");
    }
}