//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CastleDetailTab
{
    public Label labelObjective { get; private set; }

    public DropdownField comboObjective { get; private set; }

    public Label labelDiplomaticRelations { get; private set; }

    public VisualElement iconCountry { get; private set; }

    public Label labelCastleName { get; private set; }

    public Label labelCastleRegion { get; private set; }

    public VisualElement ObjectiveContainer { get; private set; }

    public VisualElement DiplomaticRelationsContainer { get; private set; }

    public VisualElement CastleBossImage { get; private set; }

    public Label labelGold { get; private set; }

    public Label labelBalance { get; private set; }

    public VisualElement MaxIncomeBar { get; private set; }

    public VisualElement CurrentIncomeBar { get; private set; }

    public Label labelIncome { get; private set; }

    public Label labelMaxIncome { get; private set; }

    public VisualElement IncomeBar { get; private set; }

    public Label labelExpenditure { get; private set; }

    public Label labelDevLevel { get; private set; }

    public Label labelTotalInvestment { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Label labelTotalPowerMax { get; private set; }

    public Label labelCastleStrength { get; private set; }

    public Button buttonToggleMemberListAndIcon { get; private set; }

    public Label labelInCastleMemberCount { get; private set; }

    public Label labelInCastleSoldierCount { get; private set; }

    public Label labelInCastleSoldierCountMax { get; private set; }

    public VisualElement InCastleMemberIconsContainer { get; private set; }

    public Label labelDeployedMemberCount { get; private set; }

    public Label labelDeployedSoldierCount { get; private set; }

    public Label labelDeployedSoldierCountMax { get; private set; }

    public VisualElement DeployedMemberIconsContainer { get; private set; }

    public CharacterTable MemberListViewTable { get; private set; }

    public VisualElement MemberIconView { get; private set; }

    public VisualElement MemberListView { get; private set; }

    public Label labelObjectiveSelectionTitle { get; private set; }

    public SimpleTable ObjectiveSelectionTargetTable { get; private set; }

    public Button buttonCancelObjectiveSelection { get; private set; }

    public VisualElement NormalView { get; private set; }

    public VisualElement ObjectiveSelectionView { get; private set; }

    public CharacterSummary CharacterSummary { get; private set; }

    public VisualElement Root { get; private set; }

    public CastleDetailTab(VisualElement root)
    {
        Root = root;
        labelObjective = Root?.Q<Label>("labelObjective");
        comboObjective = Root?.Q<DropdownField>("comboObjective");
        labelDiplomaticRelations = Root?.Q<Label>("labelDiplomaticRelations");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelCastleName = Root?.Q<Label>("labelCastleName");
        labelCastleRegion = Root?.Q<Label>("labelCastleRegion");
        ObjectiveContainer = Root?.Q<VisualElement>("ObjectiveContainer");
        DiplomaticRelationsContainer = Root?.Q<VisualElement>("DiplomaticRelationsContainer");
        CastleBossImage = Root?.Q<VisualElement>("CastleBossImage");
        labelGold = Root?.Q<Label>("labelGold");
        labelBalance = Root?.Q<Label>("labelBalance");
        MaxIncomeBar = Root?.Q<VisualElement>("MaxIncomeBar");
        CurrentIncomeBar = Root?.Q<VisualElement>("CurrentIncomeBar");
        labelIncome = Root?.Q<Label>("labelIncome");
        labelMaxIncome = Root?.Q<Label>("labelMaxIncome");
        IncomeBar = Root?.Q<VisualElement>("IncomeBar");
        labelExpenditure = Root?.Q<Label>("labelExpenditure");
        labelDevLevel = Root?.Q<Label>("labelDevLevel");
        labelTotalInvestment = Root?.Q<Label>("labelTotalInvestment");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalPowerMax = Root?.Q<Label>("labelTotalPowerMax");
        labelCastleStrength = Root?.Q<Label>("labelCastleStrength");
        buttonToggleMemberListAndIcon = Root?.Q<Button>("buttonToggleMemberListAndIcon");
        labelInCastleMemberCount = Root?.Q<Label>("labelInCastleMemberCount");
        labelInCastleSoldierCount = Root?.Q<Label>("labelInCastleSoldierCount");
        labelInCastleSoldierCountMax = Root?.Q<Label>("labelInCastleSoldierCountMax");
        InCastleMemberIconsContainer = Root?.Q<VisualElement>("InCastleMemberIconsContainer");
        labelDeployedMemberCount = Root?.Q<Label>("labelDeployedMemberCount");
        labelDeployedSoldierCount = Root?.Q<Label>("labelDeployedSoldierCount");
        labelDeployedSoldierCountMax = Root?.Q<Label>("labelDeployedSoldierCountMax");
        DeployedMemberIconsContainer = Root?.Q<VisualElement>("DeployedMemberIconsContainer");
        MemberListViewTable = new CharacterTable(Root?.Q<VisualElement>("MemberListViewTable"));
        MemberIconView = Root?.Q<VisualElement>("MemberIconView");
        MemberListView = Root?.Q<VisualElement>("MemberListView");
        labelObjectiveSelectionTitle = Root?.Q<Label>("labelObjectiveSelectionTitle");
        ObjectiveSelectionTargetTable = new SimpleTable(Root?.Q<VisualElement>("ObjectiveSelectionTargetTable"));
        buttonCancelObjectiveSelection = Root?.Q<Button>("buttonCancelObjectiveSelection");
        NormalView = Root?.Q<VisualElement>("NormalView");
        ObjectiveSelectionView = Root?.Q<VisualElement>("ObjectiveSelectionView");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelObjective = Root?.Q<Label>("labelObjective");
        comboObjective = Root?.Q<DropdownField>("comboObjective");
        labelDiplomaticRelations = Root?.Q<Label>("labelDiplomaticRelations");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelCastleName = Root?.Q<Label>("labelCastleName");
        labelCastleRegion = Root?.Q<Label>("labelCastleRegion");
        ObjectiveContainer = Root?.Q<VisualElement>("ObjectiveContainer");
        DiplomaticRelationsContainer = Root?.Q<VisualElement>("DiplomaticRelationsContainer");
        CastleBossImage = Root?.Q<VisualElement>("CastleBossImage");
        labelGold = Root?.Q<Label>("labelGold");
        labelBalance = Root?.Q<Label>("labelBalance");
        MaxIncomeBar = Root?.Q<VisualElement>("MaxIncomeBar");
        CurrentIncomeBar = Root?.Q<VisualElement>("CurrentIncomeBar");
        labelIncome = Root?.Q<Label>("labelIncome");
        labelMaxIncome = Root?.Q<Label>("labelMaxIncome");
        IncomeBar = Root?.Q<VisualElement>("IncomeBar");
        labelExpenditure = Root?.Q<Label>("labelExpenditure");
        labelDevLevel = Root?.Q<Label>("labelDevLevel");
        labelTotalInvestment = Root?.Q<Label>("labelTotalInvestment");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalPowerMax = Root?.Q<Label>("labelTotalPowerMax");
        labelCastleStrength = Root?.Q<Label>("labelCastleStrength");
        buttonToggleMemberListAndIcon = Root?.Q<Button>("buttonToggleMemberListAndIcon");
        labelInCastleMemberCount = Root?.Q<Label>("labelInCastleMemberCount");
        labelInCastleSoldierCount = Root?.Q<Label>("labelInCastleSoldierCount");
        labelInCastleSoldierCountMax = Root?.Q<Label>("labelInCastleSoldierCountMax");
        InCastleMemberIconsContainer = Root?.Q<VisualElement>("InCastleMemberIconsContainer");
        labelDeployedMemberCount = Root?.Q<Label>("labelDeployedMemberCount");
        labelDeployedSoldierCount = Root?.Q<Label>("labelDeployedSoldierCount");
        labelDeployedSoldierCountMax = Root?.Q<Label>("labelDeployedSoldierCountMax");
        DeployedMemberIconsContainer = Root?.Q<VisualElement>("DeployedMemberIconsContainer");
        MemberListViewTable = new CharacterTable(Root?.Q<VisualElement>("MemberListViewTable"));
        MemberIconView = Root?.Q<VisualElement>("MemberIconView");
        MemberListView = Root?.Q<VisualElement>("MemberListView");
        labelObjectiveSelectionTitle = Root?.Q<Label>("labelObjectiveSelectionTitle");
        ObjectiveSelectionTargetTable = new SimpleTable(Root?.Q<VisualElement>("ObjectiveSelectionTargetTable"));
        buttonCancelObjectiveSelection = Root?.Q<Button>("buttonCancelObjectiveSelection");
        NormalView = Root?.Q<VisualElement>("NormalView");
        ObjectiveSelectionView = Root?.Q<VisualElement>("ObjectiveSelectionView");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
    }
}