//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CastleTableRowItem
{
    public Label labelRegion { get; private set; }

    public Label labelObjective { get; private set; }

    public VisualElement iconCountry { get; private set; }

    public Label labelName { get; private set; }

    public VisualElement ObjectiveContainer { get; private set; }

    public Label labelGold { get; private set; }

    public Label labelBalance { get; private set; }

    public Label labelIncome { get; private set; }

    public Label labelMaxIncome { get; private set; }

    public VisualElement MaxIncomeBar { get; private set; }

    public VisualElement CurrentIncomeBar { get; private set; }

    public VisualElement IncomeBar { get; private set; }

    public Label labelExpenditure { get; private set; }

    public Label labelDevLevel { get; private set; }

    public Label labelTotalInvestment { get; private set; }

    public Label labelSoldiers { get; private set; }

    public Label labelSoldiersMax { get; private set; }

    public Label labelStrength { get; private set; }

    public Label labelMembers { get; private set; }

    public VisualElement CastleBossImage { get; private set; }

    public Button CastleTableRowItemRoot { get; private set; }

    public VisualElement Root { get; private set; }

    public CastleTableRowItem(VisualElement root)
    {
        Root = root;
        labelRegion = Root?.Q<Label>("labelRegion");
        labelObjective = Root?.Q<Label>("labelObjective");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelName = Root?.Q<Label>("labelName");
        ObjectiveContainer = Root?.Q<VisualElement>("ObjectiveContainer");
        labelGold = Root?.Q<Label>("labelGold");
        labelBalance = Root?.Q<Label>("labelBalance");
        labelIncome = Root?.Q<Label>("labelIncome");
        labelMaxIncome = Root?.Q<Label>("labelMaxIncome");
        MaxIncomeBar = Root?.Q<VisualElement>("MaxIncomeBar");
        CurrentIncomeBar = Root?.Q<VisualElement>("CurrentIncomeBar");
        IncomeBar = Root?.Q<VisualElement>("IncomeBar");
        labelExpenditure = Root?.Q<Label>("labelExpenditure");
        labelDevLevel = Root?.Q<Label>("labelDevLevel");
        labelTotalInvestment = Root?.Q<Label>("labelTotalInvestment");
        labelSoldiers = Root?.Q<Label>("labelSoldiers");
        labelSoldiersMax = Root?.Q<Label>("labelSoldiersMax");
        labelStrength = Root?.Q<Label>("labelStrength");
        labelMembers = Root?.Q<Label>("labelMembers");
        CastleBossImage = Root?.Q<VisualElement>("CastleBossImage");
        CastleTableRowItemRoot = Root?.Q<Button>("CastleTableRowItemRoot");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelRegion = Root?.Q<Label>("labelRegion");
        labelObjective = Root?.Q<Label>("labelObjective");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelName = Root?.Q<Label>("labelName");
        ObjectiveContainer = Root?.Q<VisualElement>("ObjectiveContainer");
        labelGold = Root?.Q<Label>("labelGold");
        labelBalance = Root?.Q<Label>("labelBalance");
        labelIncome = Root?.Q<Label>("labelIncome");
        labelMaxIncome = Root?.Q<Label>("labelMaxIncome");
        MaxIncomeBar = Root?.Q<VisualElement>("MaxIncomeBar");
        CurrentIncomeBar = Root?.Q<VisualElement>("CurrentIncomeBar");
        IncomeBar = Root?.Q<VisualElement>("IncomeBar");
        labelExpenditure = Root?.Q<Label>("labelExpenditure");
        labelDevLevel = Root?.Q<Label>("labelDevLevel");
        labelTotalInvestment = Root?.Q<Label>("labelTotalInvestment");
        labelSoldiers = Root?.Q<Label>("labelSoldiers");
        labelSoldiersMax = Root?.Q<Label>("labelSoldiersMax");
        labelStrength = Root?.Q<Label>("labelStrength");
        labelMembers = Root?.Q<Label>("labelMembers");
        CastleBossImage = Root?.Q<VisualElement>("CastleBossImage");
        CastleTableRowItemRoot = Root?.Q<Button>("CastleTableRowItemRoot");
    }
}