//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CastleInfoPanel
{
    public Button TabButtonCastle { get; private set; }

    public Button TabButtonCountry { get; private set; }

    public Button TabButtonDiplomacy { get; private set; }

    public CastleDetailTab CastleDetailTab { get; private set; }

    public CountryDetailTab CountryDetailTab { get; private set; }

    public VisualElement DiplomacyRelations { get; private set; }

    public ScrollView DiplomacyScrollView { get; private set; }

    public VisualElement CastleInfoTab { get; private set; }

    public VisualElement CountryInfoTab { get; private set; }

    public VisualElement DiplomacyInfoTab { get; private set; }

    public VisualElement CastleInfo { get; private set; }

    public VisualElement Root { get; private set; }

    public CastleInfoPanel(VisualElement root)
    {
        Root = root;
        TabButtonCastle = Root?.Q<Button>("TabButtonCastle");
        TabButtonCountry = Root?.Q<Button>("TabButtonCountry");
        TabButtonDiplomacy = Root?.Q<Button>("TabButtonDiplomacy");
        CastleDetailTab = new CastleDetailTab(Root?.Q<VisualElement>("CastleDetailTab"));
        CountryDetailTab = new CountryDetailTab(Root?.Q<VisualElement>("CountryDetailTab"));
        DiplomacyRelations = Root?.Q<VisualElement>("DiplomacyRelations");
        DiplomacyScrollView = Root?.Q<ScrollView>("DiplomacyScrollView");
        CastleInfoTab = Root?.Q<VisualElement>("CastleInfoTab");
        CountryInfoTab = Root?.Q<VisualElement>("CountryInfoTab");
        DiplomacyInfoTab = Root?.Q<VisualElement>("DiplomacyInfoTab");
        CastleInfo = Root?.Q<VisualElement>("CastleInfo");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        TabButtonCastle = Root?.Q<Button>("TabButtonCastle");
        TabButtonCountry = Root?.Q<Button>("TabButtonCountry");
        TabButtonDiplomacy = Root?.Q<Button>("TabButtonDiplomacy");
        CastleDetailTab = new CastleDetailTab(Root?.Q<VisualElement>("CastleDetailTab"));
        CountryDetailTab = new CountryDetailTab(Root?.Q<VisualElement>("CountryDetailTab"));
        DiplomacyRelations = Root?.Q<VisualElement>("DiplomacyRelations");
        DiplomacyScrollView = Root?.Q<ScrollView>("DiplomacyScrollView");
        CastleInfoTab = Root?.Q<VisualElement>("CastleInfoTab");
        CountryInfoTab = Root?.Q<VisualElement>("CountryInfoTab");
        DiplomacyInfoTab = Root?.Q<VisualElement>("DiplomacyInfoTab");
        CastleInfo = Root?.Q<VisualElement>("CastleInfo");
    }
}