//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterTable
{
    public Label labelHeaderName { get; private set; }

    public Label labelHeaderAttack { get; private set; }

    public Label labelHeaderDefence { get; private set; }

    public Label labelHeaderIntelligence { get; private set; }

    public Label labelHeaderGoverning { get; private set; }

    public Label labelHeaderStatus { get; private set; }

    public Label labelHeaderContribution { get; private set; }

    public Label labelHeaderPrestige { get; private set; }

    public VisualElement Header { get; private set; }

    public ListView ListView { get; private set; }

    public VisualElement Root { get; private set; }

    public CharacterTable(VisualElement root)
    {
        Root = root;
        labelHeaderName = Root?.Q<Label>("labelHeaderName");
        labelHeaderAttack = Root?.Q<Label>("labelHeaderAttack");
        labelHeaderDefence = Root?.Q<Label>("labelHeaderDefence");
        labelHeaderIntelligence = Root?.Q<Label>("labelHeaderIntelligence");
        labelHeaderGoverning = Root?.Q<Label>("labelHeaderGoverning");
        labelHeaderStatus = Root?.Q<Label>("labelHeaderStatus");
        labelHeaderContribution = Root?.Q<Label>("labelHeaderContribution");
        labelHeaderPrestige = Root?.Q<Label>("labelHeaderPrestige");
        Header = Root?.Q<VisualElement>("Header");
        ListView = Root?.Q<ListView>("ListView");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelHeaderName = Root?.Q<Label>("labelHeaderName");
        labelHeaderAttack = Root?.Q<Label>("labelHeaderAttack");
        labelHeaderDefence = Root?.Q<Label>("labelHeaderDefence");
        labelHeaderIntelligence = Root?.Q<Label>("labelHeaderIntelligence");
        labelHeaderGoverning = Root?.Q<Label>("labelHeaderGoverning");
        labelHeaderStatus = Root?.Q<Label>("labelHeaderStatus");
        labelHeaderContribution = Root?.Q<Label>("labelHeaderContribution");
        labelHeaderPrestige = Root?.Q<Label>("labelHeaderPrestige");
        Header = Root?.Q<VisualElement>("Header");
        ListView = Root?.Q<ListView>("ListView");
    }
}