//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterInfo
{
    public Label labelCharaStatus { get; private set; }

    public Label labelCharaName { get; private set; }

    public Label labelCharaAttackCaption { get; private set; }

    public Label labelCharaAttack { get; private set; }

    public Label labelCharaDefenseCaption { get; private set; }

    public Label labelCharaDefense { get; private set; }

    public Label labelCharaIntelligenceCaption { get; private set; }

    public Label labelCharaIntelligence { get; private set; }

    public Label labelCharaLoyaltyCaption { get; private set; }

    public Label labelCharaLoyalty { get; private set; }

    public Label labelCharaPrestigeCaption { get; private set; }

    public Label labelCharaPrestige { get; private set; }

    public Label labelCharaContributionCaption { get; private set; }

    public Label labelCharaContribution { get; private set; }

    public Label labelCharaSalaryRatioCaption { get; private set; }

    public Label labelCharaSalaryRatio { get; private set; }

    public Label labelCharaSoldierCountCaption { get; private set; }

    public Label labelCharaSoldierCount { get; private set; }

    public CharacterInfoSoldierIcon soldier00 { get; private set; }

    public CharacterInfoSoldierIcon soldier01 { get; private set; }

    public CharacterInfoSoldierIcon soldier02 { get; private set; }

    public CharacterInfoSoldierIcon soldier03 { get; private set; }

    public CharacterInfoSoldierIcon soldier04 { get; private set; }

    public CharacterInfoSoldierIcon soldier05 { get; private set; }

    public CharacterInfoSoldierIcon soldier06 { get; private set; }

    public CharacterInfoSoldierIcon soldier07 { get; private set; }

    public CharacterInfoSoldierIcon soldier08 { get; private set; }

    public CharacterInfoSoldierIcon soldier09 { get; private set; }

    public CharacterInfoSoldierIcon soldier10 { get; private set; }

    public CharacterInfoSoldierIcon soldier11 { get; private set; }

    public CharacterInfoSoldierIcon soldier12 { get; private set; }

    public CharacterInfoSoldierIcon soldier13 { get; private set; }

    public CharacterInfoSoldierIcon soldier14 { get; private set; }

    public VisualElement Soldiers { get; private set; }

    public VisualElement VisualElement { get; private set; }

    public Image imageChara { get; private set; }

    public VisualElement Root { get; }

    public CharacterInfo(VisualElement root)
    {
        Root = root;
        labelCharaStatus = Root?.Q<Label>("labelCharaStatus");
        labelCharaName = Root?.Q<Label>("labelCharaName");
        labelCharaAttackCaption = Root?.Q<Label>("labelCharaAttackCaption");
        labelCharaAttack = Root?.Q<Label>("labelCharaAttack");
        labelCharaDefenseCaption = Root?.Q<Label>("labelCharaDefenseCaption");
        labelCharaDefense = Root?.Q<Label>("labelCharaDefense");
        labelCharaIntelligenceCaption = Root?.Q<Label>("labelCharaIntelligenceCaption");
        labelCharaIntelligence = Root?.Q<Label>("labelCharaIntelligence");
        labelCharaLoyaltyCaption = Root?.Q<Label>("labelCharaLoyaltyCaption");
        labelCharaLoyalty = Root?.Q<Label>("labelCharaLoyalty");
        labelCharaPrestigeCaption = Root?.Q<Label>("labelCharaPrestigeCaption");
        labelCharaPrestige = Root?.Q<Label>("labelCharaPrestige");
        labelCharaContributionCaption = Root?.Q<Label>("labelCharaContributionCaption");
        labelCharaContribution = Root?.Q<Label>("labelCharaContribution");
        labelCharaSalaryRatioCaption = Root?.Q<Label>("labelCharaSalaryRatioCaption");
        labelCharaSalaryRatio = Root?.Q<Label>("labelCharaSalaryRatio");
        labelCharaSoldierCountCaption = Root?.Q<Label>("labelCharaSoldierCountCaption");
        labelCharaSoldierCount = Root?.Q<Label>("labelCharaSoldierCount");
        soldier00 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier00"));
        soldier01 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier01"));
        soldier02 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier02"));
        soldier03 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier03"));
        soldier04 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier04"));
        soldier05 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier05"));
        soldier06 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier06"));
        soldier07 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier07"));
        soldier08 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier08"));
        soldier09 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier09"));
        soldier10 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier10"));
        soldier11 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier11"));
        soldier12 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier12"));
        soldier13 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier13"));
        soldier14 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier14"));
        Soldiers = Root?.Q<VisualElement>("Soldiers");
        VisualElement = Root?.Q<VisualElement>("VisualElement");
        imageChara = Root?.Q<Image>("imageChara");
    }
}