//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterTable
{
    public Label labelHeaderName { get; private set; }

    public Button buttonToggleDisplay { get; private set; }

    public Label labelHeaderAttack { get; private set; }

    public Label labelHeaderDefence { get; private set; }

    public Label labelHeaderIntelligence { get; private set; }

    public Label labelHeaderGoverning { get; private set; }

    public Label labelHeaderSoldiers { get; private set; }

    public Label labelHeaderContribution { get; private set; }

    public Label labelHeaderPrestige { get; private set; }

    public Label labelHeaderLoyalty { get; private set; }

    public Label labelHeaderOrderIndex { get; private set; }

    public Label labelHeaderRole { get; private set; }

    public Label labelHeaderCastle { get; private set; }

    public Label labelHeaderImportance { get; private set; }

    public VisualElement Header { get; private set; }

    public ListView ListView { get; private set; }

    public VisualElement Root { get; private set; }

    public CharacterTable(VisualElement root)
    {
        Root = root;
        labelHeaderName = Root?.Q<Label>("labelHeaderName");
        buttonToggleDisplay = Root?.Q<Button>("buttonToggleDisplay");
        labelHeaderAttack = Root?.Q<Label>("labelHeaderAttack");
        labelHeaderDefence = Root?.Q<Label>("labelHeaderDefence");
        labelHeaderIntelligence = Root?.Q<Label>("labelHeaderIntelligence");
        labelHeaderGoverning = Root?.Q<Label>("labelHeaderGoverning");
        labelHeaderSoldiers = Root?.Q<Label>("labelHeaderSoldiers");
        labelHeaderContribution = Root?.Q<Label>("labelHeaderContribution");
        labelHeaderPrestige = Root?.Q<Label>("labelHeaderPrestige");
        labelHeaderLoyalty = Root?.Q<Label>("labelHeaderLoyalty");
        labelHeaderOrderIndex = Root?.Q<Label>("labelHeaderOrderIndex");
        labelHeaderRole = Root?.Q<Label>("labelHeaderRole");
        labelHeaderCastle = Root?.Q<Label>("labelHeaderCastle");
        labelHeaderImportance = Root?.Q<Label>("labelHeaderImportance");
        Header = Root?.Q<VisualElement>("Header");
        ListView = Root?.Q<ListView>("ListView");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelHeaderName = Root?.Q<Label>("labelHeaderName");
        buttonToggleDisplay = Root?.Q<Button>("buttonToggleDisplay");
        labelHeaderAttack = Root?.Q<Label>("labelHeaderAttack");
        labelHeaderDefence = Root?.Q<Label>("labelHeaderDefence");
        labelHeaderIntelligence = Root?.Q<Label>("labelHeaderIntelligence");
        labelHeaderGoverning = Root?.Q<Label>("labelHeaderGoverning");
        labelHeaderSoldiers = Root?.Q<Label>("labelHeaderSoldiers");
        labelHeaderContribution = Root?.Q<Label>("labelHeaderContribution");
        labelHeaderPrestige = Root?.Q<Label>("labelHeaderPrestige");
        labelHeaderLoyalty = Root?.Q<Label>("labelHeaderLoyalty");
        labelHeaderOrderIndex = Root?.Q<Label>("labelHeaderOrderIndex");
        labelHeaderRole = Root?.Q<Label>("labelHeaderRole");
        labelHeaderCastle = Root?.Q<Label>("labelHeaderCastle");
        labelHeaderImportance = Root?.Q<Label>("labelHeaderImportance");
        Header = Root?.Q<VisualElement>("Header");
        ListView = Root?.Q<ListView>("ListView");
    }
}