//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterSummary
{
    public Image imagePlayerFace { get; private set; }

    public Label labelMoving { get; private set; }

    public Label labelIncapacitated { get; private set; }

    public Label traitKnight { get; private set; }

    public Label traitDrillmaster { get; private set; }

    public Label traitPirate { get; private set; }

    public Label traitAdmiral { get; private set; }

    public Label traitHunter { get; private set; }

    public Label traitMountaineer { get; private set; }

    public Label traitMerchant { get; private set; }

    public Label traitDivineSpeed { get; private set; }

    public VisualElement iconCountry { get; private set; }

    public Label labelPlayerTitle { get; private set; }

    public Label labelPlayerName { get; private set; }

    public VisualElement TraitContainer { get; private set; }

    public VisualElement TraitTooltipContainer { get; private set; }

    public Label labelTraitTooltip { get; private set; }

    public Label labelAttack { get; private set; }

    public Label labelDefense { get; private set; }

    public Label labelIntelligence { get; private set; }

    public Label labelGoverning { get; private set; }

    public Label labelSoldiers { get; private set; }

    public Label labelSoldiersMax { get; private set; }

    public Label labelLoyalty { get; private set; }

    public Label labelSalary { get; private set; }

    public Label labelContribution { get; private set; }

    public Label labelPrestige { get; private set; }

    public VisualElement OrderContainer { get; private set; }

    public Label labelOrder { get; private set; }

    public CharacterInfoSoldierIcon soldier00 { get; private set; }

    public CharacterInfoSoldierIcon soldier01 { get; private set; }

    public CharacterInfoSoldierIcon soldier02 { get; private set; }

    public CharacterInfoSoldierIcon soldier03 { get; private set; }

    public CharacterInfoSoldierIcon soldier04 { get; private set; }

    public CharacterInfoSoldierIcon soldier05 { get; private set; }

    public CharacterInfoSoldierIcon soldier06 { get; private set; }

    public CharacterInfoSoldierIcon soldier07 { get; private set; }

    public CharacterInfoSoldierIcon soldier08 { get; private set; }

    public CharacterInfoSoldierIcon soldier09 { get; private set; }

    public CharacterInfoSoldierIcon soldier10 { get; private set; }

    public CharacterInfoSoldierIcon soldier11 { get; private set; }

    public CharacterInfoSoldierIcon soldier12 { get; private set; }

    public CharacterInfoSoldierIcon soldier13 { get; private set; }

    public CharacterInfoSoldierIcon soldier14 { get; private set; }

    public VisualElement StatsPanel { get; private set; }

    public VisualElement SoldierGrid { get; private set; }

    public VisualElement Root { get; private set; }

    public CharacterSummary(VisualElement root)
    {
        Root = root;
        imagePlayerFace = Root?.Q<Image>("imagePlayerFace");
        labelMoving = Root?.Q<Label>("labelMoving");
        labelIncapacitated = Root?.Q<Label>("labelIncapacitated");
        traitKnight = Root?.Q<Label>("traitKnight");
        traitDrillmaster = Root?.Q<Label>("traitDrillmaster");
        traitPirate = Root?.Q<Label>("traitPirate");
        traitAdmiral = Root?.Q<Label>("traitAdmiral");
        traitHunter = Root?.Q<Label>("traitHunter");
        traitMountaineer = Root?.Q<Label>("traitMountaineer");
        traitMerchant = Root?.Q<Label>("traitMerchant");
        traitDivineSpeed = Root?.Q<Label>("traitDivineSpeed");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelPlayerTitle = Root?.Q<Label>("labelPlayerTitle");
        labelPlayerName = Root?.Q<Label>("labelPlayerName");
        TraitContainer = Root?.Q<VisualElement>("TraitContainer");
        TraitTooltipContainer = Root?.Q<VisualElement>("TraitTooltipContainer");
        labelTraitTooltip = Root?.Q<Label>("labelTraitTooltip");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelGoverning = Root?.Q<Label>("labelGoverning");
        labelSoldiers = Root?.Q<Label>("labelSoldiers");
        labelSoldiersMax = Root?.Q<Label>("labelSoldiersMax");
        labelLoyalty = Root?.Q<Label>("labelLoyalty");
        labelSalary = Root?.Q<Label>("labelSalary");
        labelContribution = Root?.Q<Label>("labelContribution");
        labelPrestige = Root?.Q<Label>("labelPrestige");
        OrderContainer = Root?.Q<VisualElement>("OrderContainer");
        labelOrder = Root?.Q<Label>("labelOrder");
        soldier00 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier00"));
        soldier01 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier01"));
        soldier02 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier02"));
        soldier03 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier03"));
        soldier04 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier04"));
        soldier05 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier05"));
        soldier06 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier06"));
        soldier07 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier07"));
        soldier08 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier08"));
        soldier09 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier09"));
        soldier10 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier10"));
        soldier11 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier11"));
        soldier12 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier12"));
        soldier13 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier13"));
        soldier14 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier14"));
        StatsPanel = Root?.Q<VisualElement>("StatsPanel");
        SoldierGrid = Root?.Q<VisualElement>("SoldierGrid");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        imagePlayerFace = Root?.Q<Image>("imagePlayerFace");
        labelMoving = Root?.Q<Label>("labelMoving");
        labelIncapacitated = Root?.Q<Label>("labelIncapacitated");
        traitKnight = Root?.Q<Label>("traitKnight");
        traitDrillmaster = Root?.Q<Label>("traitDrillmaster");
        traitPirate = Root?.Q<Label>("traitPirate");
        traitAdmiral = Root?.Q<Label>("traitAdmiral");
        traitHunter = Root?.Q<Label>("traitHunter");
        traitMountaineer = Root?.Q<Label>("traitMountaineer");
        traitMerchant = Root?.Q<Label>("traitMerchant");
        traitDivineSpeed = Root?.Q<Label>("traitDivineSpeed");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelPlayerTitle = Root?.Q<Label>("labelPlayerTitle");
        labelPlayerName = Root?.Q<Label>("labelPlayerName");
        TraitContainer = Root?.Q<VisualElement>("TraitContainer");
        TraitTooltipContainer = Root?.Q<VisualElement>("TraitTooltipContainer");
        labelTraitTooltip = Root?.Q<Label>("labelTraitTooltip");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelGoverning = Root?.Q<Label>("labelGoverning");
        labelSoldiers = Root?.Q<Label>("labelSoldiers");
        labelSoldiersMax = Root?.Q<Label>("labelSoldiersMax");
        labelLoyalty = Root?.Q<Label>("labelLoyalty");
        labelSalary = Root?.Q<Label>("labelSalary");
        labelContribution = Root?.Q<Label>("labelContribution");
        labelPrestige = Root?.Q<Label>("labelPrestige");
        OrderContainer = Root?.Q<VisualElement>("OrderContainer");
        labelOrder = Root?.Q<Label>("labelOrder");
        soldier00 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier00"));
        soldier01 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier01"));
        soldier02 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier02"));
        soldier03 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier03"));
        soldier04 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier04"));
        soldier05 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier05"));
        soldier06 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier06"));
        soldier07 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier07"));
        soldier08 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier08"));
        soldier09 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier09"));
        soldier10 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier10"));
        soldier11 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier11"));
        soldier12 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier12"));
        soldier13 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier13"));
        soldier14 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier14"));
        StatsPanel = Root?.Q<VisualElement>("StatsPanel");
        SoldierGrid = Root?.Q<VisualElement>("SoldierGrid");
    }
}