//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterInfoPanel
{
    public Label labelActionMenuTitle { get; private set; }

    public VisualElement ActionButtonContainer { get; private set; }

    public Button buttonPrev { get; private set; }

    public Button buttonNext { get; private set; }

    public Button buttonClose { get; private set; }

    public VisualElement imageRuler { get; private set; }

    public VisualElement imageBoss { get; private set; }

    public VisualElement RulerImageContainer { get; private set; }

    public VisualElement BossImageContainer { get; private set; }

    public VisualElement imageChara { get; private set; }

    public Label labelAttack { get; private set; }

    public Label labelDefense { get; private set; }

    public Label labelIntelligence { get; private set; }

    public Label labelGoverning { get; private set; }

    public Label labelGold { get; private set; }

    public Label labelPrestige { get; private set; }

    public Label labelContribution { get; private set; }

    public Label labelLoyalty { get; private set; }

    public VisualElement Stats { get; private set; }

    public VisualElement Stats2 { get; private set; }

    public Label labelSoldierCount { get; private set; }

    public VisualElement ControlBox { get; private set; }

    public Label labelName { get; private set; }

    public Label labelStatus { get; private set; }

    public VisualElement Soldiers { get; private set; }

    public VisualElement ActionMenu { get; private set; }

    public VisualElement Root { get; private set; }

    public CharacterInfoPanel(VisualElement root)
    {
        Root = root;
        labelActionMenuTitle = Root?.Q<Label>("labelActionMenuTitle");
        ActionButtonContainer = Root?.Q<VisualElement>("ActionButtonContainer");
        buttonPrev = Root?.Q<Button>("buttonPrev");
        buttonNext = Root?.Q<Button>("buttonNext");
        buttonClose = Root?.Q<Button>("buttonClose");
        imageRuler = Root?.Q<VisualElement>("imageRuler");
        imageBoss = Root?.Q<VisualElement>("imageBoss");
        RulerImageContainer = Root?.Q<VisualElement>("RulerImageContainer");
        BossImageContainer = Root?.Q<VisualElement>("BossImageContainer");
        imageChara = Root?.Q<VisualElement>("imageChara");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelGoverning = Root?.Q<Label>("labelGoverning");
        labelGold = Root?.Q<Label>("labelGold");
        labelPrestige = Root?.Q<Label>("labelPrestige");
        labelContribution = Root?.Q<Label>("labelContribution");
        labelLoyalty = Root?.Q<Label>("labelLoyalty");
        Stats = Root?.Q<VisualElement>("Stats");
        Stats2 = Root?.Q<VisualElement>("Stats2");
        labelSoldierCount = Root?.Q<Label>("labelSoldierCount");
        ControlBox = Root?.Q<VisualElement>("ControlBox");
        labelName = Root?.Q<Label>("labelName");
        labelStatus = Root?.Q<Label>("labelStatus");
        Soldiers = Root?.Q<VisualElement>("Soldiers");
        ActionMenu = Root?.Q<VisualElement>("ActionMenu");
    }
}