//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterSummary
{
    public Label labelPlayerTitle { get; private set; }

    public Label labelPlayerName { get; private set; }

    public Label labelMoving { get; private set; }

    public Label labelAttack { get; private set; }

    public Label labelDefense { get; private set; }

    public Label labelIntelligence { get; private set; }

    public Label labelGoverning { get; private set; }

    public Label labelPlayerGold { get; private set; }

    public Label labelPlayerContribution { get; private set; }

    public Label labelPlayerPrestige { get; private set; }

    public CharacterInfoSoldierIcon soldier00 { get; private set; }

    public CharacterInfoSoldierIcon soldier01 { get; private set; }

    public CharacterInfoSoldierIcon soldier02 { get; private set; }

    public CharacterInfoSoldierIcon soldier03 { get; private set; }

    public CharacterInfoSoldierIcon soldier04 { get; private set; }

    public CharacterInfoSoldierIcon soldier05 { get; private set; }

    public CharacterInfoSoldierIcon soldier06 { get; private set; }

    public CharacterInfoSoldierIcon soldier07 { get; private set; }

    public CharacterInfoSoldierIcon soldier08 { get; private set; }

    public CharacterInfoSoldierIcon soldier09 { get; private set; }

    public CharacterInfoSoldierIcon soldier10 { get; private set; }

    public CharacterInfoSoldierIcon soldier11 { get; private set; }

    public CharacterInfoSoldierIcon soldier12 { get; private set; }

    public CharacterInfoSoldierIcon soldier13 { get; private set; }

    public CharacterInfoSoldierIcon soldier14 { get; private set; }

    public VisualElement StatsPanel { get; private set; }

    public VisualElement SoldierGrid { get; private set; }

    public Image imagePlayerFace { get; private set; }

    public VisualElement Root { get; private set; }

    public CharacterSummary(VisualElement root)
    {
        Root = root;
        labelPlayerTitle = Root?.Q<Label>("labelPlayerTitle");
        labelPlayerName = Root?.Q<Label>("labelPlayerName");
        labelMoving = Root?.Q<Label>("labelMoving");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelGoverning = Root?.Q<Label>("labelGoverning");
        labelPlayerGold = Root?.Q<Label>("labelPlayerGold");
        labelPlayerContribution = Root?.Q<Label>("labelPlayerContribution");
        labelPlayerPrestige = Root?.Q<Label>("labelPlayerPrestige");
        soldier00 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier00"));
        soldier01 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier01"));
        soldier02 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier02"));
        soldier03 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier03"));
        soldier04 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier04"));
        soldier05 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier05"));
        soldier06 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier06"));
        soldier07 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier07"));
        soldier08 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier08"));
        soldier09 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier09"));
        soldier10 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier10"));
        soldier11 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier11"));
        soldier12 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier12"));
        soldier13 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier13"));
        soldier14 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier14"));
        StatsPanel = Root?.Q<VisualElement>("StatsPanel");
        SoldierGrid = Root?.Q<VisualElement>("SoldierGrid");
        imagePlayerFace = Root?.Q<Image>("imagePlayerFace");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelPlayerTitle = Root?.Q<Label>("labelPlayerTitle");
        labelPlayerName = Root?.Q<Label>("labelPlayerName");
        labelMoving = Root?.Q<Label>("labelMoving");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelGoverning = Root?.Q<Label>("labelGoverning");
        labelPlayerGold = Root?.Q<Label>("labelPlayerGold");
        labelPlayerContribution = Root?.Q<Label>("labelPlayerContribution");
        labelPlayerPrestige = Root?.Q<Label>("labelPlayerPrestige");
        soldier00 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier00"));
        soldier01 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier01"));
        soldier02 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier02"));
        soldier03 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier03"));
        soldier04 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier04"));
        soldier05 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier05"));
        soldier06 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier06"));
        soldier07 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier07"));
        soldier08 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier08"));
        soldier09 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier09"));
        soldier10 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier10"));
        soldier11 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier11"));
        soldier12 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier12"));
        soldier13 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier13"));
        soldier14 = new CharacterInfoSoldierIcon(Root?.Q<VisualElement>("soldier14"));
        StatsPanel = Root?.Q<VisualElement>("StatsPanel");
        SoldierGrid = Root?.Q<VisualElement>("SoldierGrid");
        imagePlayerFace = Root?.Q<Image>("imagePlayerFace");
    }
}