//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterInfoSoldierIcon
{
    public Image imageSoldier { get; private set; }

    public Label labelLevel { get; private set; }

    public Label labelHp { get; private set; }

    public VisualElement HPBarValue { get; private set; }

    public VisualElement HPBarBackground { get; private set; }

    public VisualElement EXPBarValue { get; private set; }

    public VisualElement EXPBarBackground { get; private set; }

    public VisualElement panelContainer { get; private set; }

    public VisualElement HPBar { get; private set; }

    public VisualElement EXPBar { get; private set; }

    public VisualElement Root { get; private set; }

    public CharacterInfoSoldierIcon(VisualElement root)
    {
        Root = root;
        imageSoldier = Root?.Q<Image>("imageSoldier");
        labelLevel = Root?.Q<Label>("labelLevel");
        labelHp = Root?.Q<Label>("labelHp");
        HPBarValue = Root?.Q<VisualElement>("HPBarValue");
        HPBarBackground = Root?.Q<VisualElement>("HPBarBackground");
        EXPBarValue = Root?.Q<VisualElement>("EXPBarValue");
        EXPBarBackground = Root?.Q<VisualElement>("EXPBarBackground");
        panelContainer = Root?.Q<VisualElement>("panelContainer");
        HPBar = Root?.Q<VisualElement>("HPBar");
        EXPBar = Root?.Q<VisualElement>("EXPBar");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        imageSoldier = Root?.Q<Image>("imageSoldier");
        labelLevel = Root?.Q<Label>("labelLevel");
        labelHp = Root?.Q<Label>("labelHp");
        HPBarValue = Root?.Q<VisualElement>("HPBarValue");
        HPBarBackground = Root?.Q<VisualElement>("HPBarBackground");
        EXPBarValue = Root?.Q<VisualElement>("EXPBarValue");
        EXPBarBackground = Root?.Q<VisualElement>("EXPBarBackground");
        panelContainer = Root?.Q<VisualElement>("panelContainer");
        HPBar = Root?.Q<VisualElement>("HPBar");
        EXPBar = Root?.Q<VisualElement>("EXPBar");
    }
}