//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterTable
{
    public Label labelHeaderName { get; private set; }

    public Label labelHeaderAttack { get; private set; }

    public Label labelHeaderDefence { get; private set; }

    public Label labelHeaderIntelligence { get; private set; }

    public Label labelHeaderStatus { get; private set; }

    public Label labelHeaderLoyalty { get; private set; }

    public Label labelHeaderPrestige { get; private set; }

    public Label labelHeaderContribution { get; private set; }

    public Label labelHeaderSalaryRatio { get; private set; }

    public VisualElement Header { get; private set; }

    public CharacterTableRowItem row00 { get; private set; }

    public CharacterTableRowItem row01 { get; private set; }

    public CharacterTableRowItem row02 { get; private set; }

    public CharacterTableRowItem row03 { get; private set; }

    public CharacterTableRowItem row04 { get; private set; }

    public CharacterTableRowItem row05 { get; private set; }

    public CharacterTableRowItem row06 { get; private set; }

    public CharacterTableRowItem row07 { get; private set; }

    public CharacterTableRowItem row08 { get; private set; }

    public CharacterTableRowItem row09 { get; private set; }

    public VisualElement Root { get; }

    public CharacterTable(VisualElement root)
    {
        Root = root;
        labelHeaderName = Root?.Q<Label>("labelHeaderName");
        labelHeaderAttack = Root?.Q<Label>("labelHeaderAttack");
        labelHeaderDefence = Root?.Q<Label>("labelHeaderDefence");
        labelHeaderIntelligence = Root?.Q<Label>("labelHeaderIntelligence");
        labelHeaderStatus = Root?.Q<Label>("labelHeaderStatus");
        labelHeaderLoyalty = Root?.Q<Label>("labelHeaderLoyalty");
        labelHeaderPrestige = Root?.Q<Label>("labelHeaderPrestige");
        labelHeaderContribution = Root?.Q<Label>("labelHeaderContribution");
        labelHeaderSalaryRatio = Root?.Q<Label>("labelHeaderSalaryRatio");
        Header = Root?.Q<VisualElement>("Header");
        row00 = new CharacterTableRowItem(Root?.Q<VisualElement>("row00"));
        row01 = new CharacterTableRowItem(Root?.Q<VisualElement>("row01"));
        row02 = new CharacterTableRowItem(Root?.Q<VisualElement>("row02"));
        row03 = new CharacterTableRowItem(Root?.Q<VisualElement>("row03"));
        row04 = new CharacterTableRowItem(Root?.Q<VisualElement>("row04"));
        row05 = new CharacterTableRowItem(Root?.Q<VisualElement>("row05"));
        row06 = new CharacterTableRowItem(Root?.Q<VisualElement>("row06"));
        row07 = new CharacterTableRowItem(Root?.Q<VisualElement>("row07"));
        row08 = new CharacterTableRowItem(Root?.Q<VisualElement>("row08"));
        row09 = new CharacterTableRowItem(Root?.Q<VisualElement>("row09"));
    }
}