//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CharacterTableRowItem
{
    public Label labelName { get; private set; }

    public Label labelIsAttacked { get; private set; }

    public Label labelAttack { get; private set; }

    public Label labelDefense { get; private set; }

    public Label labelIntelligence { get; private set; }

    public Label labelStatus { get; private set; }

    public Label labelLoyalty { get; private set; }

    public Label labelPrestige { get; private set; }

    public Label labelContribution { get; private set; }

    public Label labelSalaryRatio { get; private set; }

    public Button CharacterTableRowItemRoot { get; private set; }

    public VisualElement Root { get; }

    public CharacterTableRowItem(VisualElement root)
    {
        Root = root;
        labelName = Root?.Q<Label>("labelName");
        labelIsAttacked = Root?.Q<Label>("labelIsAttacked");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelStatus = Root?.Q<Label>("labelStatus");
        labelLoyalty = Root?.Q<Label>("labelLoyalty");
        labelPrestige = Root?.Q<Label>("labelPrestige");
        labelContribution = Root?.Q<Label>("labelContribution");
        labelSalaryRatio = Root?.Q<Label>("labelSalaryRatio");
        CharacterTableRowItemRoot = Root?.Q<Button>("CharacterTableRowItemRoot");
    }
}