//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CountryDetailTab
{
    public Label labelCountryObjective { get; private set; }

    public DropdownField comboCountryObjective { get; private set; }

    public Label labelCountryRulerName { get; private set; }

    public VisualElement CountryObjectiveContainer { get; private set; }

    public Button buttonCountryCharacterList { get; private set; }

    public VisualElement CountryRulerImage { get; private set; }

    public Label labelTotalGold { get; private set; }

    public Label labelTotalBalance { get; private set; }

    public Label labelTotalIncome { get; private set; }

    public Label labelTotalExpenditure { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Label labelTotalGeneralCount { get; private set; }

    public Label labelCastleCount { get; private set; }


    public CharacterTable CharacterTable { get; private set; }

    public Label labelCountryObjectiveSelectTitle { get; private set; }

    public SimpleTable CountryObjectiveSimpleTable { get; private set; }

    public Button buttonBackFromCountryObjectiveSelect { get; private set; }

    public VisualElement CountryInfoNormalView { get; private set; }

    public VisualElement CountryInfoCharacterListView { get; private set; }

    public VisualElement CountryInfoObjectiveSelectView { get; private set; }

    public CharacterSummary CharacterSummary { get; private set; }

    public VisualElement CountryDetailTabContent { get; private set; }

    public VisualElement Root { get; private set; }

    public CountryDetailTab(VisualElement root)
    {
        Root = root;
        labelCountryObjective = Root?.Q<Label>("labelCountryObjective");
        comboCountryObjective = Root?.Q<DropdownField>("comboCountryObjective");
        labelCountryRulerName = Root?.Q<Label>("labelCountryRulerName");
        CountryObjectiveContainer = Root?.Q<VisualElement>("CountryObjectiveContainer");
        buttonCountryCharacterList = Root?.Q<Button>("buttonCountryCharacterList");
        CountryRulerImage = Root?.Q<VisualElement>("CountryRulerImage");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelTotalBalance = Root?.Q<Label>("labelTotalBalance");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalExpenditure = Root?.Q<Label>("labelTotalExpenditure");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalGeneralCount = Root?.Q<Label>("labelTotalGeneralCount");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        CharacterTable = new CharacterTable(Root?.Q<VisualElement>("CharacterTable"));
        labelCountryObjectiveSelectTitle = Root?.Q<Label>("labelCountryObjectiveSelectTitle");
        CountryObjectiveSimpleTable = new SimpleTable(Root?.Q<VisualElement>("CountryObjectiveSimpleTable"));
        buttonBackFromCountryObjectiveSelect = Root?.Q<Button>("buttonBackFromCountryObjectiveSelect");
        CountryInfoNormalView = Root?.Q<VisualElement>("CountryInfoNormalView");
        CountryInfoCharacterListView = Root?.Q<VisualElement>("CountryInfoCharacterListView");
        CountryInfoObjectiveSelectView = Root?.Q<VisualElement>("CountryInfoObjectiveSelectView");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        CountryDetailTabContent = Root?.Q<VisualElement>("CountryDetailTabContent");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelCountryObjective = Root?.Q<Label>("labelCountryObjective");
        comboCountryObjective = Root?.Q<DropdownField>("comboCountryObjective");
        labelCountryRulerName = Root?.Q<Label>("labelCountryRulerName");
        CountryObjectiveContainer = Root?.Q<VisualElement>("CountryObjectiveContainer");
        buttonCountryCharacterList = Root?.Q<Button>("buttonCountryCharacterList");
        CountryRulerImage = Root?.Q<VisualElement>("CountryRulerImage");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelTotalBalance = Root?.Q<Label>("labelTotalBalance");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalExpenditure = Root?.Q<Label>("labelTotalExpenditure");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalGeneralCount = Root?.Q<Label>("labelTotalGeneralCount");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        CharacterTable = new CharacterTable(Root?.Q<VisualElement>("CharacterTable"));
        labelCountryObjectiveSelectTitle = Root?.Q<Label>("labelCountryObjectiveSelectTitle");
        CountryObjectiveSimpleTable = new SimpleTable(Root?.Q<VisualElement>("CountryObjectiveSimpleTable"));
        buttonBackFromCountryObjectiveSelect = Root?.Q<Button>("buttonBackFromCountryObjectiveSelect");
        CountryInfoNormalView = Root?.Q<VisualElement>("CountryInfoNormalView");
        CountryInfoCharacterListView = Root?.Q<VisualElement>("CountryInfoCharacterListView");
        CountryInfoObjectiveSelectView = Root?.Q<VisualElement>("CountryInfoObjectiveSelectView");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        CountryDetailTabContent = Root?.Q<VisualElement>("CountryDetailTabContent");
    }
}