//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CountryTableRowItem
{
    public Label labelRelation { get; private set; }

    public VisualElement iconCountry { get; private set; }

    public Label labelRulerName { get; private set; }

    public VisualElement RelationContainer { get; private set; }

    public Label labelObjective { get; private set; }

    public Label labelTotalGold { get; private set; }

    public Label labelTotalBalance { get; private set; }

    public Label labelTotalIncome { get; private set; }

    public Label labelTotalExpenditure { get; private set; }

    public Label labelCastleCount { get; private set; }

    public Label labelTotalGeneralCount { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Label labelTotalPowerMax { get; private set; }

    public VisualElement iconRuler { get; private set; }

    public Button CountryTableRowItemRoot { get; private set; }

    public VisualElement Root { get; private set; }

    public CountryTableRowItem(VisualElement root)
    {
        Root = root;
        labelRelation = Root?.Q<Label>("labelRelation");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelRulerName = Root?.Q<Label>("labelRulerName");
        RelationContainer = Root?.Q<VisualElement>("RelationContainer");
        labelObjective = Root?.Q<Label>("labelObjective");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelTotalBalance = Root?.Q<Label>("labelTotalBalance");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalExpenditure = Root?.Q<Label>("labelTotalExpenditure");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        labelTotalGeneralCount = Root?.Q<Label>("labelTotalGeneralCount");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalPowerMax = Root?.Q<Label>("labelTotalPowerMax");
        iconRuler = Root?.Q<VisualElement>("iconRuler");
        CountryTableRowItemRoot = Root?.Q<Button>("CountryTableRowItemRoot");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelRelation = Root?.Q<Label>("labelRelation");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelRulerName = Root?.Q<Label>("labelRulerName");
        RelationContainer = Root?.Q<VisualElement>("RelationContainer");
        labelObjective = Root?.Q<Label>("labelObjective");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelTotalBalance = Root?.Q<Label>("labelTotalBalance");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalExpenditure = Root?.Q<Label>("labelTotalExpenditure");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        labelTotalGeneralCount = Root?.Q<Label>("labelTotalGeneralCount");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalPowerMax = Root?.Q<Label>("labelTotalPowerMax");
        iconRuler = Root?.Q<VisualElement>("iconRuler");
        CountryTableRowItemRoot = Root?.Q<Button>("CountryTableRowItemRoot");
    }
}