//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class CountryDetailTab
{
    public Label labelObjective { get; private set; }

    public DropdownField comboObjective { get; private set; }

    public VisualElement iconCountry { get; private set; }

    public Label labelCountryRulerName { get; private set; }

    public VisualElement ObjectiveContainer { get; private set; }

    public VisualElement CountryRulerImage { get; private set; }

    public Label labelTotalGold { get; private set; }

    public Label labelTotalBalance { get; private set; }

    public Label labelTotalIncome { get; private set; }

    public Label labelTotalExpenditure { get; private set; }

    public Label labelCastleCount { get; private set; }

    public Button buttonShowCastleList { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Label labelTotalGeneralCount { get; private set; }

    public Button buttonShowMemberList { get; private set; }

    public Button buttonShowDiplomacy { get; private set; }

    public CastleTable CastleListViewTable { get; private set; }

    public VisualElement CastleListView { get; private set; }

    public CharacterTable MemberListViewTable { get; private set; }

    public CharacterSummary CharacterSummary { get; private set; }

    public VisualElement MemberListView { get; private set; }

    public VisualElement DiplomacyView { get; private set; }

    public ScrollView DiplomacyScrollView { get; private set; }

    public VisualElement DiplomacyRelations { get; private set; }

    public Label labelObjectiveSelectionTitle { get; private set; }

    public SimpleTable ObjectiveSelectionTargetTable { get; private set; }

    public Button buttonCancelObjectiveSelection { get; private set; }

    public VisualElement NormalView { get; private set; }

    public VisualElement ObjectiveSelectionView { get; private set; }

    public VisualElement Root { get; private set; }

    public CountryDetailTab(VisualElement root)
    {
        Root = root;
        labelObjective = Root?.Q<Label>("labelObjective");
        comboObjective = Root?.Q<DropdownField>("comboObjective");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelCountryRulerName = Root?.Q<Label>("labelCountryRulerName");
        ObjectiveContainer = Root?.Q<VisualElement>("ObjectiveContainer");
        CountryRulerImage = Root?.Q<VisualElement>("CountryRulerImage");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelTotalBalance = Root?.Q<Label>("labelTotalBalance");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalExpenditure = Root?.Q<Label>("labelTotalExpenditure");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        buttonShowCastleList = Root?.Q<Button>("buttonShowCastleList");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalGeneralCount = Root?.Q<Label>("labelTotalGeneralCount");
        buttonShowMemberList = Root?.Q<Button>("buttonShowMemberList");
        buttonShowDiplomacy = Root?.Q<Button>("buttonShowDiplomacy");
        CastleListViewTable = new CastleTable(Root?.Q<VisualElement>("CastleListViewTable"));
        CastleListView = Root?.Q<VisualElement>("CastleListView");
        MemberListViewTable = new CharacterTable(Root?.Q<VisualElement>("MemberListViewTable"));
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        MemberListView = Root?.Q<VisualElement>("MemberListView");
        DiplomacyView = Root?.Q<VisualElement>("DiplomacyView");
        DiplomacyScrollView = Root?.Q<ScrollView>("DiplomacyScrollView");
        DiplomacyRelations = Root?.Q<VisualElement>("DiplomacyRelations");
        labelObjectiveSelectionTitle = Root?.Q<Label>("labelObjectiveSelectionTitle");
        ObjectiveSelectionTargetTable = new SimpleTable(Root?.Q<VisualElement>("ObjectiveSelectionTargetTable"));
        buttonCancelObjectiveSelection = Root?.Q<Button>("buttonCancelObjectiveSelection");
        NormalView = Root?.Q<VisualElement>("NormalView");
        ObjectiveSelectionView = Root?.Q<VisualElement>("ObjectiveSelectionView");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelObjective = Root?.Q<Label>("labelObjective");
        comboObjective = Root?.Q<DropdownField>("comboObjective");
        iconCountry = Root?.Q<VisualElement>("iconCountry");
        labelCountryRulerName = Root?.Q<Label>("labelCountryRulerName");
        ObjectiveContainer = Root?.Q<VisualElement>("ObjectiveContainer");
        CountryRulerImage = Root?.Q<VisualElement>("CountryRulerImage");
        labelTotalGold = Root?.Q<Label>("labelTotalGold");
        labelTotalBalance = Root?.Q<Label>("labelTotalBalance");
        labelTotalIncome = Root?.Q<Label>("labelTotalIncome");
        labelTotalExpenditure = Root?.Q<Label>("labelTotalExpenditure");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        buttonShowCastleList = Root?.Q<Button>("buttonShowCastleList");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelTotalGeneralCount = Root?.Q<Label>("labelTotalGeneralCount");
        buttonShowMemberList = Root?.Q<Button>("buttonShowMemberList");
        buttonShowDiplomacy = Root?.Q<Button>("buttonShowDiplomacy");
        CastleListViewTable = new CastleTable(Root?.Q<VisualElement>("CastleListViewTable"));
        CastleListView = Root?.Q<VisualElement>("CastleListView");
        MemberListViewTable = new CharacterTable(Root?.Q<VisualElement>("MemberListViewTable"));
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        MemberListView = Root?.Q<VisualElement>("MemberListView");
        DiplomacyView = Root?.Q<VisualElement>("DiplomacyView");
        DiplomacyScrollView = Root?.Q<ScrollView>("DiplomacyScrollView");
        DiplomacyRelations = Root?.Q<VisualElement>("DiplomacyRelations");
        labelObjectiveSelectionTitle = Root?.Q<Label>("labelObjectiveSelectionTitle");
        ObjectiveSelectionTargetTable = new SimpleTable(Root?.Q<VisualElement>("ObjectiveSelectionTargetTable"));
        buttonCancelObjectiveSelection = Root?.Q<Button>("buttonCancelObjectiveSelection");
        NormalView = Root?.Q<VisualElement>("NormalView");
        ObjectiveSelectionView = Root?.Q<VisualElement>("ObjectiveSelectionView");
    }
}