//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class ForceTable
{
    public ListView ListView { get; private set; }

    public VisualElement Root { get; private set; }

    public ForceTable(VisualElement root)
    {
        Root = root;
        ListView = Root?.Q<ListView>("ListView");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        ListView = Root?.Q<ListView>("ListView");
    }
}