//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class ForceDetailTab
{
    public Label labelForceTitle { get; private set; }

    public Label labelForceCount { get; private set; }

    public ForceTable ForceListViewTable { get; private set; }

    public VisualElement ForceListView { get; private set; }

    public VisualElement Root { get; private set; }

    public ForceDetailTab(VisualElement root)
    {
        Root = root;
        labelForceTitle = Root?.Q<Label>("labelForceTitle");
        labelForceCount = Root?.Q<Label>("labelForceCount");
        ForceListViewTable = new ForceTable(Root?.Q<VisualElement>("ForceListViewTable"));
        ForceListView = Root?.Q<VisualElement>("ForceListView");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelForceTitle = Root?.Q<Label>("labelForceTitle");
        labelForceCount = Root?.Q<Label>("labelForceCount");
        ForceListViewTable = new ForceTable(Root?.Q<VisualElement>("ForceListViewTable"));
        ForceListView = Root?.Q<VisualElement>("ForceListView");
    }
}