//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class HexInfoOverlay
{
    public VisualElement imageHexForceCharaImage { get; private set; }

    public Label labelHexForceChara { get; private set; }

    public VisualElement imageHexCountryColor { get; private set; }

    public Label labelHexOwner { get; private set; }

    public Label labelHexTerrain { get; private set; }

    public Label labelHexSettlement { get; private set; }

    public VisualElement labelHexTerrainParent { get; private set; }

    public VisualElement Root { get; }

    public HexInfoOverlay(VisualElement root)
    {
        Root = root;
        imageHexForceCharaImage = Root?.Q<VisualElement>("imageHexForceCharaImage");
        labelHexForceChara = Root?.Q<Label>("labelHexForceChara");
        imageHexCountryColor = Root?.Q<VisualElement>("imageHexCountryColor");
        labelHexOwner = Root?.Q<Label>("labelHexOwner");
        labelHexTerrain = Root?.Q<Label>("labelHexTerrain");
        labelHexSettlement = Root?.Q<Label>("labelHexSettlement");
        labelHexTerrainParent = Root?.Q<VisualElement>("labelHexTerrainParent");
    }
}