//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class MainUI
{
    [SerializeField]
    private UIDocument _document;
    public PersonalPhasePanel PersonalPhasePanel { get; private set; }

    public VisualElement MapContainer { get; private set; }

    public VisualElement UIPanelContainer { get; private set; }

    public BattleWindow BattleWindow { get; private set; }

    public MainUIFrame Frame { get; private set; }

    public TileInfoOverlay TileInfo { get; private set; }

    public TileDetailPanel TileDetail { get; private set; }

    public CharacterInfoPanel CharacterInfo { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        PersonalPhasePanel = new PersonalPhasePanel(Root?.Q<VisualElement>("PersonalPhasePanel"));
        MapContainer = Root?.Q<VisualElement>("MapContainer");
        UIPanelContainer = Root?.Q<VisualElement>("UIPanelContainer");
        BattleWindow = new BattleWindow(Root?.Q<VisualElement>("BattleWindow"));
        Frame = new MainUIFrame(Root?.Q<VisualElement>("Frame"));
        TileInfo = new TileInfoOverlay(Root?.Q<VisualElement>("TileInfo"));
        TileDetail = new TileDetailPanel(Root?.Q<VisualElement>("TileDetail"));
        CharacterInfo = new CharacterInfoPanel(Root?.Q<VisualElement>("CharacterInfo"));
    }
}