//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class MainUIFrame
{
    public Label labelCurrentDate { get; private set; }

    public Button buttonPlay { get; private set; }

    public VisualElement Root { get; }

    public MainUIFrame(VisualElement root)
    {
        Root = root;
        labelCurrentDate = Root?.Q<Label>("labelCurrentDate");
        buttonPlay = Root?.Q<Button>("buttonPlay");
    }
}