//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class MainUI
{
    [SerializeField]
    private UIDocument _document;
    public CameraMovementArea CameraMovementArea { get; private set; }

    public VisualElement UIContainer { get; private set; }

    public BattleWindow BattleWindow { get; private set; }

    public MessageWindow MessageWindow { get; private set; }

    public SystemMenuWindow SystemMenuWindow { get; private set; }

    public VisualElement WindowHost { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        CameraMovementArea = new CameraMovementArea(Root?.Q<VisualElement>("CameraMovementArea"));
        UIContainer = Root?.Q<VisualElement>("UIContainer");
        BattleWindow = new BattleWindow(Root?.Q<VisualElement>("BattleWindow"));
        MessageWindow = new MessageWindow(Root?.Q<VisualElement>("MessageWindow"));
        SystemMenuWindow = new SystemMenuWindow(Root?.Q<VisualElement>("SystemMenuWindow"));
        WindowHost = Root?.Q<VisualElement>("WindowHost");
    }

    public void ReinitializeDocument()
    {
        CameraMovementArea.ReinitializeComponent(Root?.Q<VisualElement>("CameraMovementArea"));
        UIContainer = Root?.Q<VisualElement>("UIContainer");
        BattleWindow.ReinitializeComponent(Root?.Q<VisualElement>("BattleWindow"));
        MessageWindow.ReinitializeComponent(Root?.Q<VisualElement>("MessageWindow"));
        SystemMenuWindow.ReinitializeComponent(Root?.Q<VisualElement>("SystemMenuWindow"));
        WindowHost = Root?.Q<VisualElement>("WindowHost");
    }
}