//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class MainUI
{
    [SerializeField]
    private UIDocument _document;
    public BattleWindow BattleWindow { get; private set; }

    public MainUIFrame Frame { get; private set; }

    public PersonalPhasePanel PersonalPhasePanel { get; private set; }

    public StrategyPhasePanel StrategyPhasePanel { get; private set; }

    public SelectCharacterPanel SelectCharacterPanel { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        BattleWindow = new BattleWindow(Root?.Q<VisualElement>("BattleWindow"));
        Frame = new MainUIFrame(Root?.Q<VisualElement>("Frame"));
        PersonalPhasePanel = new PersonalPhasePanel(Root?.Q<VisualElement>("PersonalPhasePanel"));
        StrategyPhasePanel = new StrategyPhasePanel(Root?.Q<VisualElement>("StrategyPhasePanel"));
        SelectCharacterPanel = new SelectCharacterPanel(Root?.Q<VisualElement>("SelectCharacterPanel"));
    }
}