//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class MainUIFrame
{
    public Button buttonPlaySpeedPlus { get; private set; }

    public Button buttonPlaySpeedMinus { get; private set; }

    public Button buttonPlaySpeed0 { get; private set; }

    public Button buttonPlaySpeed1 { get; private set; }

    public Button buttonPlaySpeed2 { get; private set; }

    public Button buttonPlaySpeed3 { get; private set; }

    public Button buttonPlaySpeed4 { get; private set; }

    public Button buttonShowSystemMenu { get; private set; }

    public Label labelCurrentDate { get; private set; }

    public Button buttonPlay { get; private set; }

    public VisualElement DatePanel { get; private set; }

    public VisualElement Root { get; }

    public MainUIFrame(VisualElement root)
    {
        Root = root;
        buttonPlaySpeedPlus = Root?.Q<Button>("buttonPlaySpeedPlus");
        buttonPlaySpeedMinus = Root?.Q<Button>("buttonPlaySpeedMinus");
        buttonPlaySpeed0 = Root?.Q<Button>("buttonPlaySpeed0");
        buttonPlaySpeed1 = Root?.Q<Button>("buttonPlaySpeed1");
        buttonPlaySpeed2 = Root?.Q<Button>("buttonPlaySpeed2");
        buttonPlaySpeed3 = Root?.Q<Button>("buttonPlaySpeed3");
        buttonPlaySpeed4 = Root?.Q<Button>("buttonPlaySpeed4");
        buttonShowSystemMenu = Root?.Q<Button>("buttonShowSystemMenu");
        labelCurrentDate = Root?.Q<Label>("labelCurrentDate");
        buttonPlay = Root?.Q<Button>("buttonPlay");
        DatePanel = Root?.Q<VisualElement>("DatePanel");
    }
}