//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class PersonalPhasePanel
{
    public Label labelDate { get; private set; }

    public Label labelMonth { get; private set; }

    public Label labelDay { get; private set; }

    public Label labelPhase { get; private set; }

    public VisualElement DateInfo { get; private set; }

    public VisualElement PhaseInfo { get; private set; }

    public Label labelPlayerName { get; private set; }

    public Label labelPlayerTitle { get; private set; }

    public Label labelPlayerGold { get; private set; }

    public Label labelPlayerAP { get; private set; }

    public Image imagePlayerFace { get; private set; }

    public VisualElement PlayerStatus { get; private set; }

    public VisualElement PlayerBasicInfo { get; private set; }

    public Button buttonDevelop { get; private set; }

    public Button buttonFortify { get; private set; }

    public Button buttonHireSoldier { get; private set; }

    public Button buttonInvest { get; private set; }

    public Button buttonTrainSoldier { get; private set; }

    public Button buttonRebel { get; private set; }

    public Button buttonResign { get; private set; }

    public VisualElement ActionButtons { get; private set; }

    public Label labelCostGold { get; private set; }

    public Label labelCostAP { get; private set; }

    public Button buttonExecute { get; private set; }

    public Label labelActionName { get; private set; }

    public Label labelActionDescription { get; private set; }

    public VisualElement CostInfo { get; private set; }

    public Label labelAttack { get; private set; }

    public Label labelDefense { get; private set; }

    public Label labelIntelligence { get; private set; }

    public Label labelGoverning { get; private set; }

    public Label labelLoyalty { get; private set; }

    public Label labelSoldierCount { get; private set; }

    public VisualElement StatsRow1 { get; private set; }

    public VisualElement StatsRow2 { get; private set; }

    public VisualElement soldierSlot00 { get; private set; }

    public VisualElement soldierSlot01 { get; private set; }

    public VisualElement soldierSlot02 { get; private set; }

    public VisualElement soldierSlot03 { get; private set; }

    public VisualElement soldierSlot04 { get; private set; }

    public VisualElement SoldierGrid { get; private set; }

    public VisualElement StatsPanel { get; private set; }

    public VisualElement SoldiersPanel { get; private set; }

    public VisualElement HeaderPanel { get; private set; }

    public VisualElement PlayerInfoPanel { get; private set; }

    public VisualElement ActionsPanel { get; private set; }

    public VisualElement ActionDetailPanel { get; private set; }

    public VisualElement CharacterDetailPanel { get; private set; }

    public VisualElement PersonalPhasePanelRoot { get; private set; }

    public VisualElement Root { get; }

    public PersonalPhasePanel(VisualElement root)
    {
        Root = root;
        labelDate = Root?.Q<Label>("labelDate");
        labelMonth = Root?.Q<Label>("labelMonth");
        labelDay = Root?.Q<Label>("labelDay");
        labelPhase = Root?.Q<Label>("labelPhase");
        DateInfo = Root?.Q<VisualElement>("DateInfo");
        PhaseInfo = Root?.Q<VisualElement>("PhaseInfo");
        labelPlayerName = Root?.Q<Label>("labelPlayerName");
        labelPlayerTitle = Root?.Q<Label>("labelPlayerTitle");
        labelPlayerGold = Root?.Q<Label>("labelPlayerGold");
        labelPlayerAP = Root?.Q<Label>("labelPlayerAP");
        imagePlayerFace = Root?.Q<Image>("imagePlayerFace");
        PlayerStatus = Root?.Q<VisualElement>("PlayerStatus");
        PlayerBasicInfo = Root?.Q<VisualElement>("PlayerBasicInfo");
        buttonDevelop = Root?.Q<Button>("buttonDevelop");
        buttonFortify = Root?.Q<Button>("buttonFortify");
        buttonHireSoldier = Root?.Q<Button>("buttonHireSoldier");
        buttonInvest = Root?.Q<Button>("buttonInvest");
        buttonTrainSoldier = Root?.Q<Button>("buttonTrainSoldier");
        buttonRebel = Root?.Q<Button>("buttonRebel");
        buttonResign = Root?.Q<Button>("buttonResign");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        labelCostGold = Root?.Q<Label>("labelCostGold");
        labelCostAP = Root?.Q<Label>("labelCostAP");
        buttonExecute = Root?.Q<Button>("buttonExecute");
        labelActionName = Root?.Q<Label>("labelActionName");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        CostInfo = Root?.Q<VisualElement>("CostInfo");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelGoverning = Root?.Q<Label>("labelGoverning");
        labelLoyalty = Root?.Q<Label>("labelLoyalty");
        labelSoldierCount = Root?.Q<Label>("labelSoldierCount");
        StatsRow1 = Root?.Q<VisualElement>("StatsRow1");
        StatsRow2 = Root?.Q<VisualElement>("StatsRow2");
        soldierSlot00 = Root?.Q<VisualElement>("soldierSlot00");
        soldierSlot01 = Root?.Q<VisualElement>("soldierSlot01");
        soldierSlot02 = Root?.Q<VisualElement>("soldierSlot02");
        soldierSlot03 = Root?.Q<VisualElement>("soldierSlot03");
        soldierSlot04 = Root?.Q<VisualElement>("soldierSlot04");
        SoldierGrid = Root?.Q<VisualElement>("SoldierGrid");
        StatsPanel = Root?.Q<VisualElement>("StatsPanel");
        SoldiersPanel = Root?.Q<VisualElement>("SoldiersPanel");
        HeaderPanel = Root?.Q<VisualElement>("HeaderPanel");
        PlayerInfoPanel = Root?.Q<VisualElement>("PlayerInfoPanel");
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
        ActionDetailPanel = Root?.Q<VisualElement>("ActionDetailPanel");
        CharacterDetailPanel = Root?.Q<VisualElement>("CharacterDetailPanel");
        PersonalPhasePanelRoot = Root?.Q<VisualElement>("PersonalPhasePanelRoot");
    }
}