//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class PersonalPhaseScreen
{
    public Label labelCurrentPersonalGold { get; private set; }

    public Button buttonTurnEnd { get; private set; }

    public Label labelCost { get; private set; }

    public Label labelActionDescription { get; private set; }

    public VisualElement ActionButtons { get; private set; }

    public VisualElement ActionsPanel { get; private set; }

    public CastleInfoPanel CastleInfoPanel { get; private set; }

    public VisualElement Root { get; private set; }

    public PersonalPhaseScreen(VisualElement root)
    {
        Root = root;
        labelCurrentPersonalGold = Root?.Q<Label>("labelCurrentPersonalGold");
        buttonTurnEnd = Root?.Q<Button>("buttonTurnEnd");
        labelCost = Root?.Q<Label>("labelCost");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
        CastleInfoPanel = new CastleInfoPanel(Root?.Q<VisualElement>("CastleInfoPanel"));
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelCurrentPersonalGold = Root?.Q<Label>("labelCurrentPersonalGold");
        buttonTurnEnd = Root?.Q<Button>("buttonTurnEnd");
        labelCost = Root?.Q<Label>("labelCost");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
        CastleInfoPanel = new CastleInfoPanel(Root?.Q<VisualElement>("CastleInfoPanel"));
    }
}