//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class PersonalPhaseScreen
{
    public Label labelCostGold { get; private set; }

    public Label labelActionDescription { get; private set; }

    public VisualElement ActionButtons { get; private set; }

    public CharacterSummary CharacterSummary { get; private set; }

    public VisualElement ActionsPanel { get; private set; }

    public VisualElement Root { get; private set; }

    public PersonalPhaseScreen(VisualElement root)
    {
        Root = root;
        labelCostGold = Root?.Q<Label>("labelCostGold");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelCostGold = Root?.Q<Label>("labelCostGold");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
    }
}