//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class PersonalPhasePanel
{
    public Label labelPlayerTitle { get; private set; }

    public Label labelPlayerName { get; private set; }

    public Label labelAttack { get; private set; }

    public Label labelDefense { get; private set; }

    public Label labelIntelligence { get; private set; }

    public Label labelGoverning { get; private set; }

    public Label labelPlayerGold { get; private set; }

    public Label labelPlayerContribution { get; private set; }

    public Label labelPlayerPrestige { get; private set; }

    public VisualElement StatsPanel { get; private set; }

    public VisualElement SoldierGrid { get; private set; }

    public Image imagePlayerFace { get; private set; }

    public Button buttonHireSoldier { get; private set; }

    public Button buttonTrainSoldier { get; private set; }

    public Button buttonDevelop { get; private set; }

    public Button buttonInvest { get; private set; }

    public Button buttonFortify { get; private set; }

    public Button buttonDeploy { get; private set; }

    public Button buttonRebel { get; private set; }

    public Button buttonResign { get; private set; }

    public Button buttonMove { get; private set; }

    public Button buttonSeize { get; private set; }

    public Button buttonGetJob { get; private set; }

    public Button buttonFinishTurn { get; private set; }

    public VisualElement ActionButtons { get; private set; }

    public Label labelActionName { get; private set; }

    public Label labelCostGold { get; private set; }

    public Label labelActionDescription { get; private set; }

    public VisualElement ActionsPanel { get; private set; }

    public VisualElement ActionDetailPanel { get; private set; }

    public VisualElement Root { get; }

    public PersonalPhasePanel(VisualElement root)
    {
        Root = root;
        labelPlayerTitle = Root?.Q<Label>("labelPlayerTitle");
        labelPlayerName = Root?.Q<Label>("labelPlayerName");
        labelAttack = Root?.Q<Label>("labelAttack");
        labelDefense = Root?.Q<Label>("labelDefense");
        labelIntelligence = Root?.Q<Label>("labelIntelligence");
        labelGoverning = Root?.Q<Label>("labelGoverning");
        labelPlayerGold = Root?.Q<Label>("labelPlayerGold");
        labelPlayerContribution = Root?.Q<Label>("labelPlayerContribution");
        labelPlayerPrestige = Root?.Q<Label>("labelPlayerPrestige");
        StatsPanel = Root?.Q<VisualElement>("StatsPanel");
        SoldierGrid = Root?.Q<VisualElement>("SoldierGrid");
        imagePlayerFace = Root?.Q<Image>("imagePlayerFace");
        buttonHireSoldier = Root?.Q<Button>("buttonHireSoldier");
        buttonTrainSoldier = Root?.Q<Button>("buttonTrainSoldier");
        buttonDevelop = Root?.Q<Button>("buttonDevelop");
        buttonInvest = Root?.Q<Button>("buttonInvest");
        buttonFortify = Root?.Q<Button>("buttonFortify");
        buttonDeploy = Root?.Q<Button>("buttonDeploy");
        buttonRebel = Root?.Q<Button>("buttonRebel");
        buttonResign = Root?.Q<Button>("buttonResign");
        buttonMove = Root?.Q<Button>("buttonMove");
        buttonSeize = Root?.Q<Button>("buttonSeize");
        buttonGetJob = Root?.Q<Button>("buttonGetJob");
        buttonFinishTurn = Root?.Q<Button>("buttonFinishTurn");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        labelActionName = Root?.Q<Label>("labelActionName");
        labelCostGold = Root?.Q<Label>("labelCostGold");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
        ActionDetailPanel = Root?.Q<VisualElement>("ActionDetailPanel");
    }
}