//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SaveDataListWindowListItem
{
    public Label labelOrderIndexCaption { get; private set; }

    public Label labelOrderIndex { get; private set; }

    public Label labelSoldiersCaption { get; private set; }

    public Label labelSoldiers { get; private set; }

    public Label labelScenarioName { get; private set; }

    public Label labelTitle { get; private set; }

    public Label labelName { get; private set; }

    public Label labelGameDate { get; private set; }

    public Label labelPhase { get; private set; }

    public Label labelCastle { get; private set; }

    public Label labelSavedTimeCaption { get; private set; }

    public Label labelSavedTime { get; private set; }

    public Image imageCharacter { get; private set; }

    public Button buttonMain { get; private set; }

    public Button buttonDownload { get; private set; }

    public Button buttonDelete { get; private set; }

    public VisualElement SaveDataLisItemRoot { get; private set; }

    public Button buttonNoData { get; private set; }

    public VisualElement Root { get; private set; }

    public SaveDataListWindowListItem(VisualElement root)
    {
        Root = root;
        labelOrderIndexCaption = Root?.Q<Label>("labelOrderIndexCaption");
        labelOrderIndex = Root?.Q<Label>("labelOrderIndex");
        labelSoldiersCaption = Root?.Q<Label>("labelSoldiersCaption");
        labelSoldiers = Root?.Q<Label>("labelSoldiers");
        labelScenarioName = Root?.Q<Label>("labelScenarioName");
        labelTitle = Root?.Q<Label>("labelTitle");
        labelName = Root?.Q<Label>("labelName");
        labelGameDate = Root?.Q<Label>("labelGameDate");
        labelPhase = Root?.Q<Label>("labelPhase");
        labelCastle = Root?.Q<Label>("labelCastle");
        labelSavedTimeCaption = Root?.Q<Label>("labelSavedTimeCaption");
        labelSavedTime = Root?.Q<Label>("labelSavedTime");
        imageCharacter = Root?.Q<Image>("imageCharacter");
        buttonMain = Root?.Q<Button>("buttonMain");
        buttonDownload = Root?.Q<Button>("buttonDownload");
        buttonDelete = Root?.Q<Button>("buttonDelete");
        SaveDataLisItemRoot = Root?.Q<VisualElement>("SaveDataLisItemRoot");
        buttonNoData = Root?.Q<Button>("buttonNoData");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelOrderIndexCaption = Root?.Q<Label>("labelOrderIndexCaption");
        labelOrderIndex = Root?.Q<Label>("labelOrderIndex");
        labelSoldiersCaption = Root?.Q<Label>("labelSoldiersCaption");
        labelSoldiers = Root?.Q<Label>("labelSoldiers");
        labelScenarioName = Root?.Q<Label>("labelScenarioName");
        labelTitle = Root?.Q<Label>("labelTitle");
        labelName = Root?.Q<Label>("labelName");
        labelGameDate = Root?.Q<Label>("labelGameDate");
        labelPhase = Root?.Q<Label>("labelPhase");
        labelCastle = Root?.Q<Label>("labelCastle");
        labelSavedTimeCaption = Root?.Q<Label>("labelSavedTimeCaption");
        labelSavedTime = Root?.Q<Label>("labelSavedTime");
        imageCharacter = Root?.Q<Image>("imageCharacter");
        buttonMain = Root?.Q<Button>("buttonMain");
        buttonDownload = Root?.Q<Button>("buttonDownload");
        buttonDelete = Root?.Q<Button>("buttonDelete");
        SaveDataLisItemRoot = Root?.Q<VisualElement>("SaveDataLisItemRoot");
        buttonNoData = Root?.Q<Button>("buttonNoData");
    }
}