//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SelectPlayerCharacterScreen
{
    public Button buttonShowFreeList { get; private set; }

    public Button buttonRandom { get; private set; }

    public Button buttonWatch { get; private set; }

    public Button buttonBackToTitle { get; private set; }

    public Label labelDescription { get; private set; }

    public CastleTableRowItem CastleInfo { get; private set; }

    public CharacterTable CharacterTable { get; private set; }

    public CharacterSummary CharacterSummary { get; private set; }

    public VisualElement Root { get; private set; }

    public SelectPlayerCharacterScreen(VisualElement root)
    {
        Root = root;
        buttonShowFreeList = Root?.Q<Button>("buttonShowFreeList");
        buttonRandom = Root?.Q<Button>("buttonRandom");
        buttonWatch = Root?.Q<Button>("buttonWatch");
        buttonBackToTitle = Root?.Q<Button>("buttonBackToTitle");
        labelDescription = Root?.Q<Label>("labelDescription");
        CastleInfo = new CastleTableRowItem(Root?.Q<VisualElement>("CastleInfo"));
        CharacterTable = new CharacterTable(Root?.Q<VisualElement>("CharacterTable"));
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        buttonShowFreeList = Root?.Q<Button>("buttonShowFreeList");
        buttonRandom = Root?.Q<Button>("buttonRandom");
        buttonWatch = Root?.Q<Button>("buttonWatch");
        buttonBackToTitle = Root?.Q<Button>("buttonBackToTitle");
        labelDescription = Root?.Q<Label>("labelDescription");
        CastleInfo = new CastleTableRowItem(Root?.Q<VisualElement>("CastleInfo"));
        CharacterTable = new CharacterTable(Root?.Q<VisualElement>("CharacterTable"));
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
    }
}