//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SelectCharacterScreen
{
    public CharacterTable CharacterTable { get; private set; }

    public CharacterSummary CharacterSummary { get; private set; }

    public Button buttonClose { get; private set; }

    public Label labelDescription { get; private set; }

    public VisualElement Root { get; private set; }

    public SelectCharacterScreen(VisualElement root)
    {
        Root = root;
        CharacterTable = new CharacterTable(Root?.Q<VisualElement>("CharacterTable"));
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        buttonClose = Root?.Q<Button>("buttonClose");
        labelDescription = Root?.Q<Label>("labelDescription");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        CharacterTable = new CharacterTable(Root?.Q<VisualElement>("CharacterTable"));
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        buttonClose = Root?.Q<Button>("buttonClose");
        labelDescription = Root?.Q<Label>("labelDescription");
    }
}