//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SelectCountryScreen
{
    public Button buttonClose { get; private set; }

    public Label labelDescription { get; private set; }

    public CountryTable CountryTable { get; private set; }

    public VisualElement Root { get; private set; }

    public SelectCountryScreen(VisualElement root)
    {
        Root = root;
        buttonClose = Root?.Q<Button>("buttonClose");
        labelDescription = Root?.Q<Label>("labelDescription");
        CountryTable = new CountryTable(Root?.Q<VisualElement>("CountryTable"));
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        buttonClose = Root?.Q<Button>("buttonClose");
        labelDescription = Root?.Q<Label>("labelDescription");
        CountryTable = new CountryTable(Root?.Q<VisualElement>("CountryTable"));
    }
}