//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SimpleTable
{
    public Label labelHeader { get; private set; }

    public VisualElement Header { get; private set; }

    public ListView ListView { get; private set; }

    public VisualElement Root { get; private set; }

    public SimpleTable(VisualElement root)
    {
        Root = root;
        labelHeader = Root?.Q<Label>("labelHeader");
        Header = Root?.Q<VisualElement>("Header");
        ListView = Root?.Q<ListView>("ListView");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelHeader = Root?.Q<Label>("labelHeader");
        Header = Root?.Q<VisualElement>("Header");
        ListView = Root?.Q<ListView>("ListView");
    }
}