//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class StrategyPhaseScreen
{
    public Button TabButtonCastle { get; private set; }

    public Button TabButtonCountry { get; private set; }

    public Button TabButtonDiplomacy { get; private set; }

    public Label labelDevLevel { get; private set; }

    public Label labelTotalInvestment { get; private set; }

    public VisualElement MaxIncomeBar { get; private set; }

    public VisualElement CurrentIncomeBar { get; private set; }

    public Label labelIncome { get; private set; }

    public Label labelMaxIncome { get; private set; }

    public VisualElement IncomeBar { get; private set; }

    public Label labelExpenditure { get; private set; }

    public Label labelGold { get; private set; }

    public Label labelBalance { get; private set; }

    public Label labelCastleStrength { get; private set; }

    public Label labelTotalPower { get; private set; }

    public Label labelGarrisonedCount { get; private set; }

    public VisualElement GarrisonedCharacterIcons { get; private set; }

    public Label labelDeployedCount { get; private set; }

    public VisualElement DeployedCharacterIcons { get; private set; }

    public Label labelRulerName { get; private set; }

    public Label labelRulerPersonality { get; private set; }

    public Label labelCountryBalance { get; private set; }

    public Label labelCountrySurplus { get; private set; }

    public Label labelCastleCount { get; private set; }

    public Label labelGeneralCount { get; private set; }

    public VisualElement DiplomacyRelations { get; private set; }

    public ScrollView DiplomacyScrollView { get; private set; }

    public VisualElement CastleInfoTab { get; private set; }

    public VisualElement CountryInfoTab { get; private set; }

    public VisualElement DiplomacyInfoTab { get; private set; }

    public Label labelCostGold { get; private set; }

    public Label labelActionDescription { get; private set; }

    public VisualElement ActionButtons { get; private set; }

    public CharacterSummary CharacterSummary { get; private set; }

    public VisualElement InfoTabPanel { get; private set; }

    public VisualElement ActionsPanel { get; private set; }

    public VisualElement Root { get; private set; }

    public StrategyPhaseScreen(VisualElement root)
    {
        Root = root;
        TabButtonCastle = Root?.Q<Button>("TabButtonCastle");
        TabButtonCountry = Root?.Q<Button>("TabButtonCountry");
        TabButtonDiplomacy = Root?.Q<Button>("TabButtonDiplomacy");
        labelDevLevel = Root?.Q<Label>("labelDevLevel");
        labelTotalInvestment = Root?.Q<Label>("labelTotalInvestment");
        MaxIncomeBar = Root?.Q<VisualElement>("MaxIncomeBar");
        CurrentIncomeBar = Root?.Q<VisualElement>("CurrentIncomeBar");
        labelIncome = Root?.Q<Label>("labelIncome");
        labelMaxIncome = Root?.Q<Label>("labelMaxIncome");
        IncomeBar = Root?.Q<VisualElement>("IncomeBar");
        labelExpenditure = Root?.Q<Label>("labelExpenditure");
        labelGold = Root?.Q<Label>("labelGold");
        labelBalance = Root?.Q<Label>("labelBalance");
        labelCastleStrength = Root?.Q<Label>("labelCastleStrength");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelGarrisonedCount = Root?.Q<Label>("labelGarrisonedCount");
        GarrisonedCharacterIcons = Root?.Q<VisualElement>("GarrisonedCharacterIcons");
        labelDeployedCount = Root?.Q<Label>("labelDeployedCount");
        DeployedCharacterIcons = Root?.Q<VisualElement>("DeployedCharacterIcons");
        labelRulerName = Root?.Q<Label>("labelRulerName");
        labelRulerPersonality = Root?.Q<Label>("labelRulerPersonality");
        labelCountryBalance = Root?.Q<Label>("labelCountryBalance");
        labelCountrySurplus = Root?.Q<Label>("labelCountrySurplus");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        labelGeneralCount = Root?.Q<Label>("labelGeneralCount");
        DiplomacyRelations = Root?.Q<VisualElement>("DiplomacyRelations");
        DiplomacyScrollView = Root?.Q<ScrollView>("DiplomacyScrollView");
        CastleInfoTab = Root?.Q<VisualElement>("CastleInfoTab");
        CountryInfoTab = Root?.Q<VisualElement>("CountryInfoTab");
        DiplomacyInfoTab = Root?.Q<VisualElement>("DiplomacyInfoTab");
        labelCostGold = Root?.Q<Label>("labelCostGold");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        InfoTabPanel = Root?.Q<VisualElement>("InfoTabPanel");
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        TabButtonCastle = Root?.Q<Button>("TabButtonCastle");
        TabButtonCountry = Root?.Q<Button>("TabButtonCountry");
        TabButtonDiplomacy = Root?.Q<Button>("TabButtonDiplomacy");
        labelDevLevel = Root?.Q<Label>("labelDevLevel");
        labelTotalInvestment = Root?.Q<Label>("labelTotalInvestment");
        MaxIncomeBar = Root?.Q<VisualElement>("MaxIncomeBar");
        CurrentIncomeBar = Root?.Q<VisualElement>("CurrentIncomeBar");
        labelIncome = Root?.Q<Label>("labelIncome");
        labelMaxIncome = Root?.Q<Label>("labelMaxIncome");
        IncomeBar = Root?.Q<VisualElement>("IncomeBar");
        labelExpenditure = Root?.Q<Label>("labelExpenditure");
        labelGold = Root?.Q<Label>("labelGold");
        labelBalance = Root?.Q<Label>("labelBalance");
        labelCastleStrength = Root?.Q<Label>("labelCastleStrength");
        labelTotalPower = Root?.Q<Label>("labelTotalPower");
        labelGarrisonedCount = Root?.Q<Label>("labelGarrisonedCount");
        GarrisonedCharacterIcons = Root?.Q<VisualElement>("GarrisonedCharacterIcons");
        labelDeployedCount = Root?.Q<Label>("labelDeployedCount");
        DeployedCharacterIcons = Root?.Q<VisualElement>("DeployedCharacterIcons");
        labelRulerName = Root?.Q<Label>("labelRulerName");
        labelRulerPersonality = Root?.Q<Label>("labelRulerPersonality");
        labelCountryBalance = Root?.Q<Label>("labelCountryBalance");
        labelCountrySurplus = Root?.Q<Label>("labelCountrySurplus");
        labelCastleCount = Root?.Q<Label>("labelCastleCount");
        labelGeneralCount = Root?.Q<Label>("labelGeneralCount");
        DiplomacyRelations = Root?.Q<VisualElement>("DiplomacyRelations");
        DiplomacyScrollView = Root?.Q<ScrollView>("DiplomacyScrollView");
        CastleInfoTab = Root?.Q<VisualElement>("CastleInfoTab");
        CountryInfoTab = Root?.Q<VisualElement>("CountryInfoTab");
        DiplomacyInfoTab = Root?.Q<VisualElement>("DiplomacyInfoTab");
        labelCostGold = Root?.Q<Label>("labelCostGold");
        labelActionDescription = Root?.Q<Label>("labelActionDescription");
        ActionButtons = Root?.Q<VisualElement>("ActionButtons");
        CharacterSummary = new CharacterSummary(Root?.Q<VisualElement>("CharacterSummary"));
        InfoTabPanel = Root?.Q<VisualElement>("InfoTabPanel");
        ActionsPanel = Root?.Q<VisualElement>("ActionsPanel");
    }
}