//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SystemSettingWindow
{
    public DropdownField comboOrientation { get; private set; }

    public Button buttonPlaySpeed0 { get; private set; }

    public Button buttonPlaySpeed1 { get; private set; }

    public Button buttonPlaySpeed2 { get; private set; }

    public Button buttonPlaySpeed3 { get; private set; }

    public Button buttonPlaySpeed4 { get; private set; }

    public DropdownField comboAutoSaveFrequency { get; private set; }

    public DropdownField comboCountryEliminatedNotification { get; private set; }

    public VisualElement OrientationContainer { get; private set; }

    public Label labelSaveDataListWindowTitle { get; private set; }

    public Button CloseButton { get; private set; }

    public VisualElement Border { get; private set; }

    public VisualElement Root { get; private set; }

    public SystemSettingWindow(VisualElement root)
    {
        Root = root;
        comboOrientation = Root?.Q<DropdownField>("comboOrientation");
        buttonPlaySpeed0 = Root?.Q<Button>("buttonPlaySpeed0");
        buttonPlaySpeed1 = Root?.Q<Button>("buttonPlaySpeed1");
        buttonPlaySpeed2 = Root?.Q<Button>("buttonPlaySpeed2");
        buttonPlaySpeed3 = Root?.Q<Button>("buttonPlaySpeed3");
        buttonPlaySpeed4 = Root?.Q<Button>("buttonPlaySpeed4");
        comboAutoSaveFrequency = Root?.Q<DropdownField>("comboAutoSaveFrequency");
        comboCountryEliminatedNotification = Root?.Q<DropdownField>("comboCountryEliminatedNotification");
        OrientationContainer = Root?.Q<VisualElement>("OrientationContainer");
        labelSaveDataListWindowTitle = Root?.Q<Label>("labelSaveDataListWindowTitle");
        CloseButton = Root?.Q<Button>("CloseButton");
        Border = Root?.Q<VisualElement>("Border");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        comboOrientation = Root?.Q<DropdownField>("comboOrientation");
        buttonPlaySpeed0 = Root?.Q<Button>("buttonPlaySpeed0");
        buttonPlaySpeed1 = Root?.Q<Button>("buttonPlaySpeed1");
        buttonPlaySpeed2 = Root?.Q<Button>("buttonPlaySpeed2");
        buttonPlaySpeed3 = Root?.Q<Button>("buttonPlaySpeed3");
        buttonPlaySpeed4 = Root?.Q<Button>("buttonPlaySpeed4");
        comboAutoSaveFrequency = Root?.Q<DropdownField>("comboAutoSaveFrequency");
        comboCountryEliminatedNotification = Root?.Q<DropdownField>("comboCountryEliminatedNotification");
        OrientationContainer = Root?.Q<VisualElement>("OrientationContainer");
        labelSaveDataListWindowTitle = Root?.Q<Label>("labelSaveDataListWindowTitle");
        CloseButton = Root?.Q<Button>("CloseButton");
        Border = Root?.Q<VisualElement>("Border");
    }
}