//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SystemSettingsWindow
{
    public DropdownField comboOrientation { get; private set; }

    public DropdownField comboLayout { get; private set; }

    public Label labelSaveDataListWindowTitle { get; private set; }

    public Button CloseButton { get; private set; }

    public VisualElement Border { get; private set; }

    public VisualElement Root { get; }

    public SystemSettingsWindow(VisualElement root)
    {
        Root = root;
        comboOrientation = Root?.Q<DropdownField>("comboOrientation");
        comboLayout = Root?.Q<DropdownField>("comboLayout");
        labelSaveDataListWindowTitle = Root?.Q<Label>("labelSaveDataListWindowTitle");
        CloseButton = Root?.Q<Button>("CloseButton");
        Border = Root?.Q<VisualElement>("Border");
    }
}