//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SystemSettingWindow
{
    public DropdownField comboOrientation { get; private set; }

    public Button buttonPlaySpeed0 { get; private set; }

    public Button buttonPlaySpeed1 { get; private set; }

    public Button buttonPlaySpeed2 { get; private set; }

    public Button buttonPlaySpeed3 { get; private set; }

    public Button buttonPlaySpeed4 { get; private set; }

    public DropdownField comboAutoSaveFrequency { get; private set; }

    public DropdownField comboCountryEliminatedNotification { get; private set; }

    public DropdownField comboEdgeScrollEnabled { get; private set; }

    public Button buttonBattleModeSelfManual { get; private set; }

    public Button buttonBattleModeSelfWatch { get; private set; }

    public Button buttonBattleModeSelfDoubleSpeed { get; private set; }

    public Button buttonBattleModeSelfSkip { get; private set; }

    public Button buttonBattleModeOwnCastleWatch { get; private set; }

    public Button buttonBattleModeOwnCastleDoubleSpeed { get; private set; }

    public Button buttonBattleModeOwnCastleSkip { get; private set; }

    public Button buttonBattleModeSubordinateWatch { get; private set; }

    public Button buttonBattleModeSubordinateDoubleSpeed { get; private set; }

    public Button buttonBattleModeSubordinateSkip { get; private set; }

    public Button buttonBattleModeOwnCountryWatch { get; private set; }

    public Button buttonBattleModeOwnCountryDoubleSpeed { get; private set; }

    public Button buttonBattleModeOwnCountrySkip { get; private set; }

    public DropdownField comboPauseAfterBattle { get; private set; }

    public VisualElement OrientationContainer { get; private set; }

    public Label labelSaveDataListWindowTitle { get; private set; }

    public Button CloseButton { get; private set; }

    public VisualElement Border { get; private set; }

    public VisualElement Root { get; private set; }

    public SystemSettingWindow(VisualElement root)
    {
        Root = root;
        comboOrientation = Root?.Q<DropdownField>("comboOrientation");
        buttonPlaySpeed0 = Root?.Q<Button>("buttonPlaySpeed0");
        buttonPlaySpeed1 = Root?.Q<Button>("buttonPlaySpeed1");
        buttonPlaySpeed2 = Root?.Q<Button>("buttonPlaySpeed2");
        buttonPlaySpeed3 = Root?.Q<Button>("buttonPlaySpeed3");
        buttonPlaySpeed4 = Root?.Q<Button>("buttonPlaySpeed4");
        comboAutoSaveFrequency = Root?.Q<DropdownField>("comboAutoSaveFrequency");
        comboCountryEliminatedNotification = Root?.Q<DropdownField>("comboCountryEliminatedNotification");
        comboEdgeScrollEnabled = Root?.Q<DropdownField>("comboEdgeScrollEnabled");
        buttonBattleModeSelfManual = Root?.Q<Button>("buttonBattleModeSelfManual");
        buttonBattleModeSelfWatch = Root?.Q<Button>("buttonBattleModeSelfWatch");
        buttonBattleModeSelfDoubleSpeed = Root?.Q<Button>("buttonBattleModeSelfDoubleSpeed");
        buttonBattleModeSelfSkip = Root?.Q<Button>("buttonBattleModeSelfSkip");
        buttonBattleModeOwnCastleWatch = Root?.Q<Button>("buttonBattleModeOwnCastleWatch");
        buttonBattleModeOwnCastleDoubleSpeed = Root?.Q<Button>("buttonBattleModeOwnCastleDoubleSpeed");
        buttonBattleModeOwnCastleSkip = Root?.Q<Button>("buttonBattleModeOwnCastleSkip");
        buttonBattleModeSubordinateWatch = Root?.Q<Button>("buttonBattleModeSubordinateWatch");
        buttonBattleModeSubordinateDoubleSpeed = Root?.Q<Button>("buttonBattleModeSubordinateDoubleSpeed");
        buttonBattleModeSubordinateSkip = Root?.Q<Button>("buttonBattleModeSubordinateSkip");
        buttonBattleModeOwnCountryWatch = Root?.Q<Button>("buttonBattleModeOwnCountryWatch");
        buttonBattleModeOwnCountryDoubleSpeed = Root?.Q<Button>("buttonBattleModeOwnCountryDoubleSpeed");
        buttonBattleModeOwnCountrySkip = Root?.Q<Button>("buttonBattleModeOwnCountrySkip");
        comboPauseAfterBattle = Root?.Q<DropdownField>("comboPauseAfterBattle");
        OrientationContainer = Root?.Q<VisualElement>("OrientationContainer");
        labelSaveDataListWindowTitle = Root?.Q<Label>("labelSaveDataListWindowTitle");
        CloseButton = Root?.Q<Button>("CloseButton");
        Border = Root?.Q<VisualElement>("Border");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        comboOrientation = Root?.Q<DropdownField>("comboOrientation");
        buttonPlaySpeed0 = Root?.Q<Button>("buttonPlaySpeed0");
        buttonPlaySpeed1 = Root?.Q<Button>("buttonPlaySpeed1");
        buttonPlaySpeed2 = Root?.Q<Button>("buttonPlaySpeed2");
        buttonPlaySpeed3 = Root?.Q<Button>("buttonPlaySpeed3");
        buttonPlaySpeed4 = Root?.Q<Button>("buttonPlaySpeed4");
        comboAutoSaveFrequency = Root?.Q<DropdownField>("comboAutoSaveFrequency");
        comboCountryEliminatedNotification = Root?.Q<DropdownField>("comboCountryEliminatedNotification");
        comboEdgeScrollEnabled = Root?.Q<DropdownField>("comboEdgeScrollEnabled");
        buttonBattleModeSelfManual = Root?.Q<Button>("buttonBattleModeSelfManual");
        buttonBattleModeSelfWatch = Root?.Q<Button>("buttonBattleModeSelfWatch");
        buttonBattleModeSelfDoubleSpeed = Root?.Q<Button>("buttonBattleModeSelfDoubleSpeed");
        buttonBattleModeSelfSkip = Root?.Q<Button>("buttonBattleModeSelfSkip");
        buttonBattleModeOwnCastleWatch = Root?.Q<Button>("buttonBattleModeOwnCastleWatch");
        buttonBattleModeOwnCastleDoubleSpeed = Root?.Q<Button>("buttonBattleModeOwnCastleDoubleSpeed");
        buttonBattleModeOwnCastleSkip = Root?.Q<Button>("buttonBattleModeOwnCastleSkip");
        buttonBattleModeSubordinateWatch = Root?.Q<Button>("buttonBattleModeSubordinateWatch");
        buttonBattleModeSubordinateDoubleSpeed = Root?.Q<Button>("buttonBattleModeSubordinateDoubleSpeed");
        buttonBattleModeSubordinateSkip = Root?.Q<Button>("buttonBattleModeSubordinateSkip");
        buttonBattleModeOwnCountryWatch = Root?.Q<Button>("buttonBattleModeOwnCountryWatch");
        buttonBattleModeOwnCountryDoubleSpeed = Root?.Q<Button>("buttonBattleModeOwnCountryDoubleSpeed");
        buttonBattleModeOwnCountrySkip = Root?.Q<Button>("buttonBattleModeOwnCountrySkip");
        comboPauseAfterBattle = Root?.Q<DropdownField>("comboPauseAfterBattle");
        OrientationContainer = Root?.Q<VisualElement>("OrientationContainer");
        labelSaveDataListWindowTitle = Root?.Q<Label>("labelSaveDataListWindowTitle");
        CloseButton = Root?.Q<Button>("CloseButton");
        Border = Root?.Q<VisualElement>("Border");
    }
}