//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class SystemMenuWindow
{
    public Label labelTitle { get; private set; }

    public Button buttonClose { get; private set; }

    public Button buttonSave { get; private set; }

    public Button buttonChangePlayer { get; private set; }

    public Button buttonGoToTitle { get; private set; }

    public VisualElement Root { get; private set; }

    public SystemMenuWindow(VisualElement root)
    {
        Root = root;
        labelTitle = Root?.Q<Label>("labelTitle");
        buttonClose = Root?.Q<Button>("buttonClose");
        buttonSave = Root?.Q<Button>("buttonSave");
        buttonChangePlayer = Root?.Q<Button>("buttonChangePlayer");
        buttonGoToTitle = Root?.Q<Button>("buttonGoToTitle");
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        labelTitle = Root?.Q<Label>("labelTitle");
        buttonClose = Root?.Q<Button>("buttonClose");
        buttonSave = Root?.Q<Button>("buttonSave");
        buttonChangePlayer = Root?.Q<Button>("buttonChangePlayer");
        buttonGoToTitle = Root?.Q<Button>("buttonGoToTitle");
    }
}