//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class TileInfoScreen
{
    public Button buttonClose { get; private set; }

    public CastleInfoPanel CastleInfoPanel { get; private set; }

    public VisualElement Root { get; private set; }

    public TileInfoScreen(VisualElement root)
    {
        Root = root;
        buttonClose = Root?.Q<Button>("buttonClose");
        CastleInfoPanel = new CastleInfoPanel(Root?.Q<VisualElement>("CastleInfoPanel"));
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        buttonClose = Root?.Q<Button>("buttonClose");
        CastleInfoPanel = new CastleInfoPanel(Root?.Q<VisualElement>("CastleInfoPanel"));
    }
}