//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class TileInfoOverlay
{
    public VisualElement imageTileForceCharaImage { get; private set; }

    public Label labelTileForce { get; private set; }

    public VisualElement imageTileCountryColor { get; private set; }

    public Label labelTileOwner { get; private set; }

    public Label labelTileTerrain { get; private set; }

    public Label labelTileHasCastle { get; private set; }

    public Label labelTileHasTown { get; private set; }

    public VisualElement labelTileTerrainParent { get; private set; }

    public VisualElement labelTileForceParent { get; private set; }

    public VisualElement labelTileOwnerParent { get; private set; }

    public VisualElement Root { get; private set; }

    public TileInfoOverlay(VisualElement root)
    {
        Root = root;
        imageTileForceCharaImage = Root?.Q<VisualElement>("imageTileForceCharaImage");
        labelTileForce = Root?.Q<Label>("labelTileForce");
        imageTileCountryColor = Root?.Q<VisualElement>("imageTileCountryColor");
        labelTileOwner = Root?.Q<Label>("labelTileOwner");
        labelTileTerrain = Root?.Q<Label>("labelTileTerrain");
        labelTileHasCastle = Root?.Q<Label>("labelTileHasCastle");
        labelTileHasTown = Root?.Q<Label>("labelTileHasTown");
        labelTileTerrainParent = Root?.Q<VisualElement>("labelTileTerrainParent");
        labelTileForceParent = Root?.Q<VisualElement>("labelTileForceParent");
        labelTileOwnerParent = Root?.Q<VisualElement>("labelTileOwnerParent");
    }
}