//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class TileDetailPanel
{
    public Label labelActionMenuTitle { get; private set; }

    public VisualElement ActionButtonContainer { get; private set; }

    public VisualElement imageTileCountryColor { get; private set; }

    public Label labelTileOwner { get; private set; }

    public Label labelTileTerrain { get; private set; }

    public VisualElement labelTileTerrainParent { get; private set; }

    public Button buttonCastleMembers { get; private set; }

    public Button buttonCastleGoverning { get; private set; }

    public Button buttonCastleMartial { get; private set; }

    public Button buttonCastleStrategy { get; private set; }

    public Label labelGovernor { get; private set; }

    public Label labelCastleStrength { get; private set; }

    public Label labelCastleFood { get; private set; }

    public Label labelCastleGold { get; private set; }

    public Button buttonTownGoverning { get; private set; }

    public Label labelTownFoodIncome { get; private set; }

    public Label labelTownGoldIncome { get; private set; }

    public Foldout CastleInfo { get; private set; }

    public Foldout TownInfo { get; private set; }

    public VisualElement ActionMenu { get; private set; }

    public VisualElement Root { get; private set; }

    public TileDetailPanel(VisualElement root)
    {
        Root = root;
        labelActionMenuTitle = Root?.Q<Label>("labelActionMenuTitle");
        ActionButtonContainer = Root?.Q<VisualElement>("ActionButtonContainer");
        imageTileCountryColor = Root?.Q<VisualElement>("imageTileCountryColor");
        labelTileOwner = Root?.Q<Label>("labelTileOwner");
        labelTileTerrain = Root?.Q<Label>("labelTileTerrain");
        labelTileTerrainParent = Root?.Q<VisualElement>("labelTileTerrainParent");
        buttonCastleMembers = Root?.Q<Button>("buttonCastleMembers");
        buttonCastleGoverning = Root?.Q<Button>("buttonCastleGoverning");
        buttonCastleMartial = Root?.Q<Button>("buttonCastleMartial");
        buttonCastleStrategy = Root?.Q<Button>("buttonCastleStrategy");
        labelGovernor = Root?.Q<Label>("labelGovernor");
        labelCastleStrength = Root?.Q<Label>("labelCastleStrength");
        labelCastleFood = Root?.Q<Label>("labelCastleFood");
        labelCastleGold = Root?.Q<Label>("labelCastleGold");
        buttonTownGoverning = Root?.Q<Button>("buttonTownGoverning");
        labelTownFoodIncome = Root?.Q<Label>("labelTownFoodIncome");
        labelTownGoldIncome = Root?.Q<Label>("labelTownGoldIncome");
        CastleInfo = Root?.Q<Foldout>("CastleInfo");
        TownInfo = Root?.Q<Foldout>("TownInfo");
        ActionMenu = Root?.Q<VisualElement>("ActionMenu");
    }
}