//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class TileDetailPanel
{
    public Button buttonImproveCastleStrength { get; private set; }

    public Button buttonImproveFoodIncome { get; private set; }

    public Button buttonImproveGoldIncome { get; private set; }

    public Button buttonBuildNewTown { get; private set; }

    public Button buttonAttack { get; private set; }

    public Button buttonRebel { get; private set; }

    public Button buttonBecomeIndependent { get; private set; }

    public Button buttonHireSoldier { get; private set; }

    public Button buttonTrainSoldier { get; private set; }

    public Button buttonRecruit { get; private set; }

    public Button buttonAlly { get; private set; }

    public Button buttonFireVassal { get; private set; }

    public Button buttonResign { get; private set; }

    public Button buttonShowCharacterList { get; private set; }

    public VisualElement imageTileCountryColor { get; private set; }

    public Label labelTileOwner { get; private set; }

    public Label labelTileTerrain { get; private set; }

    public VisualElement labelTileTerrainParent { get; private set; }

    public Label labelGovernor { get; private set; }

    public Label labelCastleStrength { get; private set; }

    public Label labelCastleFood { get; private set; }

    public Label labelCastleGold { get; private set; }

    public Label labelTownFoodIncome { get; private set; }

    public Label labelTownGoldIncome { get; private set; }

    public Foldout CastleInfo { get; private set; }

    public Foldout TownInfo { get; private set; }

    public VisualElement Root { get; }

    public TileDetailPanel(VisualElement root)
    {
        Root = root;
        buttonImproveCastleStrength = Root?.Q<Button>("buttonImproveCastleStrength");
        buttonImproveFoodIncome = Root?.Q<Button>("buttonImproveFoodIncome");
        buttonImproveGoldIncome = Root?.Q<Button>("buttonImproveGoldIncome");
        buttonBuildNewTown = Root?.Q<Button>("buttonBuildNewTown");
        buttonAttack = Root?.Q<Button>("buttonAttack");
        buttonRebel = Root?.Q<Button>("buttonRebel");
        buttonBecomeIndependent = Root?.Q<Button>("buttonBecomeIndependent");
        buttonHireSoldier = Root?.Q<Button>("buttonHireSoldier");
        buttonTrainSoldier = Root?.Q<Button>("buttonTrainSoldier");
        buttonRecruit = Root?.Q<Button>("buttonRecruit");
        buttonAlly = Root?.Q<Button>("buttonAlly");
        buttonFireVassal = Root?.Q<Button>("buttonFireVassal");
        buttonResign = Root?.Q<Button>("buttonResign");
        buttonShowCharacterList = Root?.Q<Button>("buttonShowCharacterList");
        imageTileCountryColor = Root?.Q<VisualElement>("imageTileCountryColor");
        labelTileOwner = Root?.Q<Label>("labelTileOwner");
        labelTileTerrain = Root?.Q<Label>("labelTileTerrain");
        labelTileTerrainParent = Root?.Q<VisualElement>("labelTileTerrainParent");
        labelGovernor = Root?.Q<Label>("labelGovernor");
        labelCastleStrength = Root?.Q<Label>("labelCastleStrength");
        labelCastleFood = Root?.Q<Label>("labelCastleFood");
        labelCastleGold = Root?.Q<Label>("labelCastleGold");
        labelTownFoodIncome = Root?.Q<Label>("labelTownFoodIncome");
        labelTownGoldIncome = Root?.Q<Label>("labelTownGoldIncome");
        CastleInfo = Root?.Q<Foldout>("CastleInfo");
        TownInfo = Root?.Q<Foldout>("TownInfo");
    }
}