//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using UnityEngine.UIElements;

public partial class TitleSceneUI
{
    [SerializeField]
    private UIDocument _document;
    public Button buttonShowSystemSettings { get; private set; }

    public Button buttonShowLicense { get; private set; }

    public SaveDataListWindow SaveDataList { get; private set; }

    public Button buttonCloseApplication { get; private set; }

    public Button buttonCloseNewGameWindow { get; private set; }

    public Button buttonStartNewGameScenario1 { get; private set; }

    public Button buttonStartNewGameScenario2 { get; private set; }

    public Button buttonLoadTextData { get; private set; }

    public Button buttonCopyFromSlot1 { get; private set; }

    public Button buttonCopyFromSlot2 { get; private set; }

    public Button buttonCopyFromSlot3 { get; private set; }

    public Button buttonCopyFromSlot4 { get; private set; }

    public Button buttonCopyFromSlot5 { get; private set; }

    public Button buttonCopyFromSlotAuto { get; private set; }

    public Button buttonClearText { get; private set; }

    public Button buttonPasteText { get; private set; }

    public Label labelTextBoxWindowTitle { get; private set; }

    public Button buttonCloseTextBoxWindow { get; private set; }

    public TextField textTextBoxWindow { get; private set; }

    public Button buttonCopyText { get; private set; }

    public Button buttonSubmitText { get; private set; }

    public Label labelProgressWindowTitle { get; private set; }

    public ProgressBar progressLoading { get; private set; }

    public Label labelLicenseWindowTitle { get; private set; }

    public Button buttonCloseLicenseWindow { get; private set; }

    public TextField textLicenseWindow { get; private set; }

    public VisualElement NewGameMenu { get; private set; }

    public VisualElement TextBoxWindow { get; private set; }

    public VisualElement ProgressWindow { get; private set; }

    public VisualElement LicenseWindow { get; private set; }

    public SystemSettingWindow SystemSettingWindow { get; private set; }

    public MessageWindow MessageWindow { get; private set; }

    public VisualElement Windows { get; private set; }

    public VisualElement Root => _document?.rootVisualElement;
    public void InitializeDocument()
    {
        buttonShowSystemSettings = Root?.Q<Button>("buttonShowSystemSettings");
        buttonShowLicense = Root?.Q<Button>("buttonShowLicense");
        SaveDataList = new SaveDataListWindow(Root?.Q<VisualElement>("SaveDataList"));
        buttonCloseApplication = Root?.Q<Button>("buttonCloseApplication");
        buttonCloseNewGameWindow = Root?.Q<Button>("buttonCloseNewGameWindow");
        buttonStartNewGameScenario1 = Root?.Q<Button>("buttonStartNewGameScenario1");
        buttonStartNewGameScenario2 = Root?.Q<Button>("buttonStartNewGameScenario2");
        buttonLoadTextData = Root?.Q<Button>("buttonLoadTextData");
        buttonCopyFromSlot1 = Root?.Q<Button>("buttonCopyFromSlot1");
        buttonCopyFromSlot2 = Root?.Q<Button>("buttonCopyFromSlot2");
        buttonCopyFromSlot3 = Root?.Q<Button>("buttonCopyFromSlot3");
        buttonCopyFromSlot4 = Root?.Q<Button>("buttonCopyFromSlot4");
        buttonCopyFromSlot5 = Root?.Q<Button>("buttonCopyFromSlot5");
        buttonCopyFromSlotAuto = Root?.Q<Button>("buttonCopyFromSlotAuto");
        buttonClearText = Root?.Q<Button>("buttonClearText");
        buttonPasteText = Root?.Q<Button>("buttonPasteText");
        labelTextBoxWindowTitle = Root?.Q<Label>("labelTextBoxWindowTitle");
        buttonCloseTextBoxWindow = Root?.Q<Button>("buttonCloseTextBoxWindow");
        textTextBoxWindow = Root?.Q<TextField>("textTextBoxWindow");
        buttonCopyText = Root?.Q<Button>("buttonCopyText");
        buttonSubmitText = Root?.Q<Button>("buttonSubmitText");
        labelProgressWindowTitle = Root?.Q<Label>("labelProgressWindowTitle");
        progressLoading = Root?.Q<ProgressBar>("progressLoading");
        labelLicenseWindowTitle = Root?.Q<Label>("labelLicenseWindowTitle");
        buttonCloseLicenseWindow = Root?.Q<Button>("buttonCloseLicenseWindow");
        textLicenseWindow = Root?.Q<TextField>("textLicenseWindow");
        NewGameMenu = Root?.Q<VisualElement>("NewGameMenu");
        TextBoxWindow = Root?.Q<VisualElement>("TextBoxWindow");
        ProgressWindow = Root?.Q<VisualElement>("ProgressWindow");
        LicenseWindow = Root?.Q<VisualElement>("LicenseWindow");
        SystemSettingWindow = new SystemSettingWindow(Root?.Q<VisualElement>("SystemSettingWindow"));
        MessageWindow = new MessageWindow(Root?.Q<VisualElement>("MessageWindow"));
        Windows = Root?.Q<VisualElement>("Windows");
    }

    public void ReinitializeDocument()
    {
        buttonShowSystemSettings = Root?.Q<Button>("buttonShowSystemSettings");
        buttonShowLicense = Root?.Q<Button>("buttonShowLicense");
        SaveDataList.ReinitializeComponent(Root?.Q<VisualElement>("SaveDataList"));
        buttonCloseApplication = Root?.Q<Button>("buttonCloseApplication");
        buttonCloseNewGameWindow = Root?.Q<Button>("buttonCloseNewGameWindow");
        buttonStartNewGameScenario1 = Root?.Q<Button>("buttonStartNewGameScenario1");
        buttonStartNewGameScenario2 = Root?.Q<Button>("buttonStartNewGameScenario2");
        buttonLoadTextData = Root?.Q<Button>("buttonLoadTextData");
        buttonCopyFromSlot1 = Root?.Q<Button>("buttonCopyFromSlot1");
        buttonCopyFromSlot2 = Root?.Q<Button>("buttonCopyFromSlot2");
        buttonCopyFromSlot3 = Root?.Q<Button>("buttonCopyFromSlot3");
        buttonCopyFromSlot4 = Root?.Q<Button>("buttonCopyFromSlot4");
        buttonCopyFromSlot5 = Root?.Q<Button>("buttonCopyFromSlot5");
        buttonCopyFromSlotAuto = Root?.Q<Button>("buttonCopyFromSlotAuto");
        buttonClearText = Root?.Q<Button>("buttonClearText");
        buttonPasteText = Root?.Q<Button>("buttonPasteText");
        labelTextBoxWindowTitle = Root?.Q<Label>("labelTextBoxWindowTitle");
        buttonCloseTextBoxWindow = Root?.Q<Button>("buttonCloseTextBoxWindow");
        textTextBoxWindow = Root?.Q<TextField>("textTextBoxWindow");
        buttonCopyText = Root?.Q<Button>("buttonCopyText");
        buttonSubmitText = Root?.Q<Button>("buttonSubmitText");
        labelProgressWindowTitle = Root?.Q<Label>("labelProgressWindowTitle");
        progressLoading = Root?.Q<ProgressBar>("progressLoading");
        labelLicenseWindowTitle = Root?.Q<Label>("labelLicenseWindowTitle");
        buttonCloseLicenseWindow = Root?.Q<Button>("buttonCloseLicenseWindow");
        textLicenseWindow = Root?.Q<TextField>("textLicenseWindow");
        NewGameMenu = Root?.Q<VisualElement>("NewGameMenu");
        TextBoxWindow = Root?.Q<VisualElement>("TextBoxWindow");
        ProgressWindow = Root?.Q<VisualElement>("ProgressWindow");
        LicenseWindow = Root?.Q<VisualElement>("LicenseWindow");
        SystemSettingWindow.ReinitializeComponent(Root?.Q<VisualElement>("SystemSettingWindow"));
        MessageWindow.ReinitializeComponent(Root?.Q<VisualElement>("MessageWindow"));
        Windows = Root?.Q<VisualElement>("Windows");
    }
}