//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rosalina Code Generator tool.
//     Version: 4.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

public partial class TransportScreen
{
    public Slider sliderAmount { get; private set; }

    public Button buttonMinus10 { get; private set; }

    public Button buttonPlus10 { get; private set; }

    public Label labelAmount { get; private set; }

    public Button buttonClose { get; private set; }

    public Label labelDescription { get; private set; }

    public CastleTable CastleTable { get; private set; }

    public VisualElement Root { get; private set; }

    public TransportScreen(VisualElement root)
    {
        Root = root;
        sliderAmount = Root?.Q<Slider>("sliderAmount");
        buttonMinus10 = Root?.Q<Button>("buttonMinus10");
        buttonPlus10 = Root?.Q<Button>("buttonPlus10");
        labelAmount = Root?.Q<Label>("labelAmount");
        buttonClose = Root?.Q<Button>("buttonClose");
        labelDescription = Root?.Q<Label>("labelDescription");
        CastleTable = new CastleTable(Root?.Q<VisualElement>("CastleTable"));
    }

    public void ReinitializeComponent(VisualElement root)
    {
        Root = root;
        sliderAmount = Root?.Q<Slider>("sliderAmount");
        buttonMinus10 = Root?.Q<Button>("buttonMinus10");
        buttonPlus10 = Root?.Q<Button>("buttonPlus10");
        labelAmount = Root?.Q<Label>("labelAmount");
        buttonClose = Root?.Q<Button>("buttonClose");
        labelDescription = Root?.Q<Label>("labelDescription");
        CastleTable = new CastleTable(Root?.Q<VisualElement>("CastleTable"));
    }
}